CREATE VIEW IF NOT EXISTS poe_trade.v_ml_v3_iron_ring_wide_training_poc
(
    `as_of_ts` DateTime64(3, 'UTC'),
    `item_id` Nullable(String),
    `identity_key` String,
    `rarity` LowCardinality(String),
    `ilvl` UInt16,
    `corrupted` UInt8,
    `fractured` UInt8,
    `synthesised` UInt8,
    `support_count_recent` UInt32,
    `mod_token_count` UInt64,
    `target_price_chaos` Float64,
    `target_fast_sale_24h_price` Nullable(Float64),
    `target_sale_probability_24h` Nullable(Float32),
    `target_likely_sold` Nullable(UInt8),
    `label_weight` Float32,
    `added_physical_damage_to_attacks_value` Float64,
    `added_cold_damage_to_attacks_value` Float64,
    `added_lightning_damage_to_attacks_value` Float64,
    `increased_cast_speed_value` Float64,
    `increased_damage_value` Float64,
    `life_regeneration_value` Float64,
    `all_attributes_value` Float64,
    `all_elemental_resistances_value` Float64,
    `chaos_resistance_value` Float64,
    `dexterity_value` Float64,
    `fire_resistance_value` Float64,
    `lightning_resistance_value` Float64,
    `maximum_energy_shield_value` Float64,
    `maximum_life_value` Float64,
    `maximum_mana_value` Float64,
    `discipline_aura_effect_value` Float64,
    `chilling_towers_freeze_duration_value` Float64,
    `meteor_towers_burning_ground_duration_value` Float64,
    `added_physical_damage_to_attacks_tier` UInt8,
    `added_cold_damage_to_attacks_tier` UInt8,
    `added_lightning_damage_to_attacks_tier` UInt8,
    `increased_cast_speed_tier` UInt8,
    `increased_damage_tier` UInt8,
    `life_regeneration_tier` UInt8,
    `all_attributes_tier` UInt8,
    `all_elemental_resistances_tier` UInt8,
    `chaos_resistance_tier` UInt8,
    `dexterity_tier` UInt8,
    `fire_resistance_tier` UInt8,
    `lightning_resistance_tier` UInt8,
    `maximum_energy_shield_tier` UInt8,
    `maximum_life_tier` UInt8,
    `maximum_mana_tier` UInt8,
    `discipline_aura_effect_tier` UInt8,
    `chilling_towers_freeze_duration_tier` UInt8,
    `meteor_towers_burning_ground_duration_tier` UInt8,
    `added_physical_damage_to_attacks_quality_score` Float64,
    `added_cold_damage_to_attacks_quality_score` Float64,
    `added_lightning_damage_to_attacks_quality_score` Float64,
    `increased_cast_speed_quality_score` Float64,
    `increased_damage_quality_score` Float64,
    `life_regeneration_quality_score` Float64,
    `all_attributes_quality_score` Float64,
    `all_elemental_resistances_quality_score` Float64,
    `chaos_resistance_quality_score` Float64,
    `dexterity_quality_score` Float64,
    `fire_resistance_quality_score` Float64,
    `lightning_resistance_quality_score` Float64,
    `maximum_energy_shield_quality_score` Float64,
    `maximum_life_quality_score` Float64,
    `maximum_mana_quality_score` Float64,
    `discipline_aura_effect_quality_score` Float64,
    `chilling_towers_freeze_duration_quality_score` Float64,
    `meteor_towers_burning_ground_duration_quality_score` Float64,
    `recognized_affix_count` UInt64
)
AS SELECT
    as_of_ts,
    item_id,
    identity_key,
    rarity,
    ilvl,
    corrupted,
    fractured,
    synthesised,
    support_count_recent,
    mod_token_count,
    target_price_chaos,
    target_fast_sale_24h_price,
    target_sale_probability_24h,
    target_likely_sold,
    label_weight,
    added_physical_damage_to_attacks_value,
    added_cold_damage_to_attacks_value,
    added_lightning_damage_to_attacks_value,
    increased_cast_speed_value,
    increased_damage_value,
    life_regeneration_value,
    all_attributes_value,
    all_elemental_resistances_value,
    chaos_resistance_value,
    dexterity_value,
    fire_resistance_value,
    lightning_resistance_value,
    maximum_energy_shield_value,
    maximum_life_value,
    maximum_mana_value,
    discipline_aura_effect_value,
    chilling_towers_freeze_duration_value,
    meteor_towers_burning_ground_duration_value,
    if(added_physical_damage_to_attacks_value > 0, greatest(1, least(9, toUInt8(ceil((added_physical_damage_to_attacks_value / 39.) * 9)))), 0) AS added_physical_damage_to_attacks_tier,
    if(added_cold_damage_to_attacks_value > 0, greatest(1, least(10, toUInt8(ceil((added_cold_damage_to_attacks_value / 86.) * 10)))), 0) AS added_cold_damage_to_attacks_tier,
    if(added_lightning_damage_to_attacks_value > 0, greatest(1, least(9, toUInt8(ceil((added_lightning_damage_to_attacks_value / 155.) * 9)))), 0) AS added_lightning_damage_to_attacks_tier,
    if(increased_cast_speed_value > 0, greatest(1, least(7, toUInt8(ceil((increased_cast_speed_value / 49.) * 7)))), 0) AS increased_cast_speed_tier,
    if(increased_damage_value > 0, greatest(1, least(3, toUInt8(ceil((increased_damage_value / 25.) * 3)))), 0) AS increased_damage_tier,
    if(life_regeneration_value > 0, greatest(1, least(9, toUInt8(ceil((life_regeneration_value / 10560.) * 9)))), 0) AS life_regeneration_tier,
    if(all_attributes_value > 0, greatest(1, least(8, toUInt8(ceil((all_attributes_value / 35.) * 8)))), 0) AS all_attributes_tier,
    if(all_elemental_resistances_value > 0, greatest(1, least(6, toUInt8(ceil((all_elemental_resistances_value / 18.) * 6)))), 0) AS all_elemental_resistances_tier,
    if(chaos_resistance_value > 0, greatest(1, least(6, toUInt8(ceil((chaos_resistance_value / 35.) * 6)))), 0) AS chaos_resistance_tier,
    if(dexterity_value > 0, greatest(1, least(10, toUInt8(ceil((dexterity_value / 60.) * 10)))), 0) AS dexterity_tier,
    if(fire_resistance_value > 0, greatest(1, least(8, toUInt8(ceil((fire_resistance_value / 48.) * 8)))), 0) AS fire_resistance_tier,
    if(lightning_resistance_value > 0, greatest(1, least(8, toUInt8(ceil((lightning_resistance_value / 48.) * 8)))), 0) AS lightning_resistance_tier,
    if(maximum_energy_shield_value > 0, greatest(1, least(12, toUInt8(ceil((maximum_energy_shield_value / 100.) * 12)))), 0) AS maximum_energy_shield_tier,
    if(maximum_life_value > 0, greatest(1, least(12, toUInt8(ceil((maximum_life_value / 189.) * 12)))), 0) AS maximum_life_tier,
    if(maximum_mana_value > 0, greatest(1, least(13, toUInt8(ceil((maximum_mana_value / 229.) * 13)))), 0) AS maximum_mana_tier,
    if(discipline_aura_effect_value > 0, greatest(1, least(1, toUInt8(ceil((discipline_aura_effect_value / 15.) * 1)))), 0) AS discipline_aura_effect_tier,
    if(chilling_towers_freeze_duration_value > 0, greatest(1, least(1, toUInt8(ceil((chilling_towers_freeze_duration_value / 0.2) * 1)))), 0) AS chilling_towers_freeze_duration_tier,
    if(meteor_towers_burning_ground_duration_value > 0, greatest(1, least(1, toUInt8(ceil((meteor_towers_burning_ground_duration_value / 3.) * 1)))), 0) AS meteor_towers_burning_ground_duration_tier,
    if(added_physical_damage_to_attacks_value > 0, least(1., added_physical_damage_to_attacks_value / 39.), 0.) AS added_physical_damage_to_attacks_quality_score,
    if(added_cold_damage_to_attacks_value > 0, least(1., added_cold_damage_to_attacks_value / 86.), 0.) AS added_cold_damage_to_attacks_quality_score,
    if(added_lightning_damage_to_attacks_value > 0, least(1., added_lightning_damage_to_attacks_value / 155.), 0.) AS added_lightning_damage_to_attacks_quality_score,
    if(increased_cast_speed_value > 0, least(1., increased_cast_speed_value / 49.), 0.) AS increased_cast_speed_quality_score,
    if(increased_damage_value > 0, least(1., increased_damage_value / 25.), 0.) AS increased_damage_quality_score,
    if(life_regeneration_value > 0, least(1., life_regeneration_value / 10560.), 0.) AS life_regeneration_quality_score,
    if(all_attributes_value > 0, least(1., all_attributes_value / 35.), 0.) AS all_attributes_quality_score,
    if(all_elemental_resistances_value > 0, least(1., all_elemental_resistances_value / 18.), 0.) AS all_elemental_resistances_quality_score,
    if(chaos_resistance_value > 0, least(1., chaos_resistance_value / 35.), 0.) AS chaos_resistance_quality_score,
    if(dexterity_value > 0, least(1., dexterity_value / 60.), 0.) AS dexterity_quality_score,
    if(fire_resistance_value > 0, least(1., fire_resistance_value / 48.), 0.) AS fire_resistance_quality_score,
    if(lightning_resistance_value > 0, least(1., lightning_resistance_value / 48.), 0.) AS lightning_resistance_quality_score,
    if(maximum_energy_shield_value > 0, least(1., maximum_energy_shield_value / 100.), 0.) AS maximum_energy_shield_quality_score,
    if(maximum_life_value > 0, least(1., maximum_life_value / 189.), 0.) AS maximum_life_quality_score,
    if(maximum_mana_value > 0, least(1., maximum_mana_value / 229.), 0.) AS maximum_mana_quality_score,
    if(discipline_aura_effect_value > 0, least(1., discipline_aura_effect_value / 15.), 0.) AS discipline_aura_effect_quality_score,
    if(chilling_towers_freeze_duration_value > 0, least(1., chilling_towers_freeze_duration_value / 0.2), 0.) AS chilling_towers_freeze_duration_quality_score,
    if(meteor_towers_burning_ground_duration_value > 0, least(1., meteor_towers_burning_ground_duration_value / 3.), 0.) AS meteor_towers_burning_ground_duration_quality_score,
    recognized_affix_count
FROM
(
    SELECT
        as_of_ts,
        item_id,
        identity_key,
        rarity,
        ilvl,
        corrupted,
        fractured,
        synthesised,
        support_count_recent,
        target_price_chaos,
        target_fast_sale_24h_price,
        target_sale_probability_24h,
        target_likely_sold,
        label_weight,
        countIf(mod_line != '') AS mod_token_count,
        maxIf(mod_value, affix_key = 'addstophysicaldamagetoattacks') AS added_physical_damage_to_attacks_value,
        maxIf(mod_value, affix_key = 'addstocolddamagetoattacks') AS added_cold_damage_to_attacks_value,
        maxIf(mod_value, affix_key = 'addstolightningdamagetoattacks') AS added_lightning_damage_to_attacks_value,
        maxIf(mod_value, affix_key = 'increasedcastspeed') AS increased_cast_speed_value,
        maxIf(mod_value, affix_key = 'increaseddamage') AS increased_damage_value,
        maxIf(mod_value, affix_key = 'regeneratelifepersecond') AS life_regeneration_value,
        maxIf(mod_value, affix_key = 'toallattributes') AS all_attributes_value,
        maxIf(mod_value, affix_key = 'toallelementalresistances') AS all_elemental_resistances_value,
        maxIf(mod_value, affix_key = 'tochaosresistance') AS chaos_resistance_value,
        maxIf(mod_value, affix_key = 'todexterity') AS dexterity_value,
        maxIf(mod_value, affix_key = 'tofireresistance') AS fire_resistance_value,
        maxIf(mod_value, affix_key = 'tolightningresistance') AS lightning_resistance_value,
        maxIf(mod_value, affix_key = 'tomaximumenergyshield') AS maximum_energy_shield_value,
        maxIf(mod_value, affix_key = 'tomaximumlife') AS maximum_life_value,
        maxIf(mod_value, affix_key = 'tomaximummana') AS maximum_mana_value,
        maxIf(mod_value, affix_key = 'disciplinehasincreasedauraeffect') AS discipline_aura_effect_value,
        maxIf(mod_value, affix_key = 'yourchillingtowersfreezeenemiesforsecondswhiletheyareaffectedbychillingbeams') AS chilling_towers_freeze_duration_value,
        maxIf(mod_value, affix_key = 'yourmeteortowerscreateburninggroundforsecondsonhit') AS meteor_towers_burning_ground_duration_value,
        countIf(mod_value > 0) AS recognized_affix_count
    FROM
    (
        SELECT
            t.as_of_ts,
            t.item_id,
            t.identity_key,
            t.rarity,
            t.ilvl,
            t.corrupted,
            t.fractured,
            t.synthesised,
            t.support_count_recent,
            t.target_price_chaos,
            t.target_fast_sale_24h_price,
            t.target_sale_probability_24h,
            t.target_likely_sold,
            t.label_weight,
            extract(o.affix_payload_json, '"explicit":\\[(.*?)\\],"implicit":') AS explicit_blob,
            extract(o.affix_payload_json, '"implicit":\\[(.*?)\\],"crafted":') AS implicit_blob,
            extract(o.affix_payload_json, '"crafted":\\[(.*?)\\],"fractured":') AS crafted_blob,
            extract(o.affix_payload_json, '"fractured":\\[(.*?)\\],"enchant":') AS fractured_blob,
            extract(o.affix_payload_json, '"enchant":\\[(.*?)\\]}') AS enchant_blob,
            arrayJoin(
                if(
                    empty(arrayConcat(
                        extractAll(explicit_blob, '"([^"]+)"'),
                        extractAll(implicit_blob, '"([^"]+)"'),
                        extractAll(crafted_blob, '"([^"]+)"'),
                        extractAll(fractured_blob, '"([^"]+)"'),
                        extractAll(enchant_blob, '"([^"]+)"')
                    )),
                    [''],
                    arrayConcat(
                        extractAll(explicit_blob, '"([^"]+)"'),
                        extractAll(implicit_blob, '"([^"]+)"'),
                        extractAll(crafted_blob, '"([^"]+)"'),
                        extractAll(fractured_blob, '"([^"]+)"'),
                        extractAll(enchant_blob, '"([^"]+)"')
                    )
                )
            ) AS mod_line,
            replaceRegexpAll(replaceRegexpAll(replaceRegexpAll(replaceAll(lowerUTF8(trimBoth(replaceAll(mod_line, '"', ''))), '\\d+(?:\\.\\d+)?', '{N}'), '\\{[nN]\\}', ''), '[^a-z]+', ''), '^$', '') AS affix_key,
            if(empty(extractAll(mod_line, '\\d+(?:\\.\\d+)?')), 0., arrayReduce('max', arrayMap(x -> toFloat64OrZero(x), extractAll(mod_line, '\\d+(?:\\.\\d+)?')))) AS mod_value
        FROM poe_trade.ml_v3_training_examples AS t
        INNER JOIN poe_trade.silver_v3_item_observations AS o ON (o.league = t.league) AND (o.item_id = t.item_id) AND (o.observed_at = t.as_of_ts)
        WHERE (t.league = 'Mirage') AND (t.category = 'ring') AND (t.base_type = 'Iron Ring') AND (t.target_price_chaos > 0)
    ) AS raw_lines
    GROUP BY
        as_of_ts,
        item_id,
        identity_key,
        rarity,
        ilvl,
        corrupted,
        fractured,
        synthesised,
        support_count_recent,
        target_price_chaos,
        target_fast_sale_24h_price,
        target_sale_probability_24h,
        target_likely_sold,
        label_weight
) AS item_rows;
