CREATE OR REPLACE VIEW poe_trade.v_ml_v3_iron_ring_wide_training_poc AS
SELECT
    as_of_ts,
    item_id,
    identity_key,
    rarity,
    ilvl,
    corrupted,
    fractured,
    synthesised,
    support_count_recent,
    mod_token_count,
    target_price_chaos,
    target_fast_sale_24h_price,
    target_sale_probability_24h,
    target_likely_sold,
    label_weight,
    all_attributes_value,
    all_attributes_tier,
    all_attributes_quality_score,
    all_resistances_value,
    all_resistances_tier,
    all_resistances_quality_score,
    chance_to_suppress_spells_value,
    chance_to_suppress_spells_tier,
    chance_to_suppress_spells_quality_score,
    chaos_resistance_value,
    chaos_resistance_tier,
    chaos_resistance_quality_score,
    cold_damage_value,
    cold_damage_tier,
    cold_damage_quality_score,
    cold_damage_percentage_value,
    cold_damage_percentage_tier,
    cold_damage_percentage_quality_score,
    cold_resistance_value,
    cold_resistance_tier,
    cold_resistance_quality_score,
    damage_taken_gained_as_life_value,
    damage_taken_gained_as_life_tier,
    damage_taken_gained_as_life_quality_score,
    dexterity_value,
    dexterity_tier,
    dexterity_quality_score,
    energy_shield_delay_value,
    energy_shield_delay_tier,
    energy_shield_delay_quality_score,
    energy_shield_regeneration_value,
    energy_shield_regeneration_tier,
    energy_shield_regeneration_quality_score,
    fire_damage_value,
    fire_damage_tier,
    fire_damage_quality_score,
    fire_damage_percentage_value,
    fire_damage_percentage_tier,
    fire_damage_percentage_quality_score,
    fire_resistance_value,
    fire_resistance_tier,
    fire_resistance_quality_score,
    increased_accuracy_value,
    increased_accuracy_tier,
    increased_accuracy_quality_score,
    increased_attack_speed_value,
    increased_attack_speed_tier,
    increased_attack_speed_quality_score,
    increased_cast_speed_value,
    increased_cast_speed_tier,
    increased_cast_speed_quality_score,
    increased_energy_shield_value,
    increased_energy_shield_tier,
    increased_energy_shield_quality_score,
    increased_evasion_rating_value,
    increased_evasion_rating_tier,
    increased_evasion_rating_quality_score,
    increased_life_value,
    increased_life_tier,
    increased_life_quality_score,
    increased_mana_value,
    increased_mana_tier,
    increased_mana_quality_score,
    increased_weapon_elemental_damage_percent_value,
    increased_weapon_elemental_damage_percent_tier,
    increased_weapon_elemental_damage_percent_quality_score,
    intelligence_value,
    intelligence_tier,
    intelligence_quality_score,
    item_found_rarity_increase_value,
    item_found_rarity_increase_tier,
    item_found_rarity_increase_quality_score,
    life_gain_per_target_value,
    life_gain_per_target_tier,
    life_gain_per_target_quality_score,
    life_gained_from_enemy_death_value,
    life_gained_from_enemy_death_tier,
    life_gained_from_enemy_death_quality_score,
    life_leech_value,
    life_leech_tier,
    life_leech_quality_score,
    life_regeneration_value,
    life_regeneration_tier,
    life_regeneration_quality_score,
    life_regeneration_rate_value,
    life_regeneration_rate_tier,
    life_regeneration_rate_quality_score,
    light_radius_increased_global_accuracy_rating_value,
    light_radius_increased_global_accuracy_rating_tier,
    light_radius_increased_global_accuracy_rating_quality_score,
    light_radius_to_accuracy_rating_value,
    light_radius_to_accuracy_rating_tier,
    light_radius_to_accuracy_rating_quality_score,
    lightning_damage_value,
    lightning_damage_tier,
    lightning_damage_quality_score,
    lightning_damage_percentage_value,
    lightning_damage_percentage_tier,
    lightning_damage_percentage_quality_score,
    lightning_resistance_value,
    lightning_resistance_tier,
    lightning_resistance_quality_score,
    mana_gained_from_enemy_death_value,
    mana_gained_from_enemy_death_tier,
    mana_gained_from_enemy_death_quality_score,
    mana_leech_value,
    mana_leech_tier,
    mana_leech_quality_score,
    mana_regeneration_value,
    mana_regeneration_tier,
    mana_regeneration_quality_score,
    physical_damage_value,
    physical_damage_tier,
    physical_damage_quality_score,
    reduced_physical_damage_taken_value,
    reduced_physical_damage_taken_tier,
    reduced_physical_damage_taken_quality_score,
    strength_value,
    strength_tier,
    strength_quality_score,
    recognized_affix_count
FROM (
    SELECT
        as_of_ts,
        item_id,
        identity_key,
        rarity,
        ilvl,
        corrupted,
        fractured,
        synthesised,
        support_count_recent,
        target_price_chaos,
        target_fast_sale_24h_price,
        target_sale_probability_24h,
        target_likely_sold,
        label_weight,
        countIf(mod_line != '') AS mod_token_count,
        maxIf(mod_value, affix_key = 'toallattributes') AS all_attributes_value,
        if(all_attributes_value > 0, greatest(1, least(4, toUInt8(ceil((all_attributes_value / 16.0) * 4)))), 0) AS all_attributes_tier,
        if(all_attributes_value > 0, least(1., all_attributes_value / 16.0), 0.) AS all_attributes_quality_score,
        maxIf(mod_value, affix_key = 'toallelementalresistances') AS all_resistances_value,
        if(all_resistances_value > 0, greatest(1, least(5, toUInt8(ceil((all_resistances_value / 16.0) * 5)))), 0) AS all_resistances_tier,
        if(all_resistances_value > 0, least(1., all_resistances_value / 16.0), 0.) AS all_resistances_quality_score,
        maxIf(mod_value, affix_key = 'chancetosuppressspelldamage') AS chance_to_suppress_spells_value,
        if(chance_to_suppress_spells_value > 0, greatest(1, least(10, toUInt8(ceil((chance_to_suppress_spells_value / 22.0) * 10)))), 0) AS chance_to_suppress_spells_tier,
        if(chance_to_suppress_spells_value > 0, least(1., chance_to_suppress_spells_value / 22.0), 0.) AS chance_to_suppress_spells_quality_score,
        maxIf(mod_value, affix_key = 'tochaosresistance') AS chaos_resistance_value,
        if(chaos_resistance_value > 0, greatest(1, least(6, toUInt8(ceil((chaos_resistance_value / 35.0) * 6)))), 0) AS chaos_resistance_tier,
        if(chaos_resistance_value > 0, least(1., chaos_resistance_value / 35.0), 0.) AS chaos_resistance_quality_score,
        maxIf(mod_value, affix_key = 'addstocolddamagetoattacks') AS cold_damage_value,
        if(cold_damage_value > 0, greatest(1, least(9, toUInt8(ceil((cold_damage_value / 40.0) * 9)))), 0) AS cold_damage_tier,
        if(cold_damage_value > 0, least(1., cold_damage_value / 40.0), 0.) AS cold_damage_quality_score,
        maxIf(mod_value, affix_key = 'increasedcolddamage') AS cold_damage_percentage_value,
        if(cold_damage_percentage_value > 0, greatest(1, least(4, toUInt8(ceil((cold_damage_percentage_value / 22.0) * 4)))), 0) AS cold_damage_percentage_tier,
        if(cold_damage_percentage_value > 0, least(1., cold_damage_percentage_value / 22.0), 0.) AS cold_damage_percentage_quality_score,
        maxIf(mod_value, affix_key = 'tocoldresistance') AS cold_resistance_value,
        if(cold_resistance_value > 0, greatest(1, least(8, toUInt8(ceil((cold_resistance_value / 48.0) * 8)))), 0) AS cold_resistance_tier,
        if(cold_resistance_value > 0, least(1., cold_resistance_value / 48.0), 0.) AS cold_resistance_quality_score,
        maxIf(mod_value, affix_key = 'ofdamagetakenrecoupedaslife') AS damage_taken_gained_as_life_value,
        if(damage_taken_gained_as_life_value > 0, greatest(1, least(4, toUInt8(ceil((damage_taken_gained_as_life_value / 15.0) * 4)))), 0) AS damage_taken_gained_as_life_tier,
        if(damage_taken_gained_as_life_value > 0, least(1., damage_taken_gained_as_life_value / 15.0), 0.) AS damage_taken_gained_as_life_quality_score,
        maxIf(mod_value, affix_key = 'todexterity') AS dexterity_value,
        if(dexterity_value > 0, greatest(1, least(9, toUInt8(ceil((dexterity_value / 55.0) * 9)))), 0) AS dexterity_tier,
        if(dexterity_value > 0, least(1., dexterity_value / 55.0), 0.) AS dexterity_quality_score,
        maxIf(mod_value, affix_key = 'fasterstartofenergyshieldrecharge') AS energy_shield_delay_value,
        if(energy_shield_delay_value > 0, greatest(1, least(5, toUInt8(ceil((energy_shield_delay_value / 66.0) * 5)))), 0) AS energy_shield_delay_tier,
        if(energy_shield_delay_value > 0, least(1., energy_shield_delay_value / 66.0), 0.) AS energy_shield_delay_quality_score,
        maxIf(mod_value, affix_key = 'increasedenergyshieldrechargerate') AS energy_shield_regeneration_value,
        if(energy_shield_regeneration_value > 0, greatest(1, least(5, toUInt8(ceil((energy_shield_regeneration_value / 38.0) * 5)))), 0) AS energy_shield_regeneration_tier,
        if(energy_shield_regeneration_value > 0, least(1., energy_shield_regeneration_value / 38.0), 0.) AS energy_shield_regeneration_quality_score,
        maxIf(mod_value, affix_key = 'addstofiredamagetoattacks') AS fire_damage_value,
        if(fire_damage_value > 0, greatest(1, least(9, toUInt8(ceil((fire_damage_value / 45.0) * 9)))), 0) AS fire_damage_tier,
        if(fire_damage_value > 0, least(1., fire_damage_value / 45.0), 0.) AS fire_damage_quality_score,
        maxIf(mod_value, affix_key = 'increasedfiredamage') AS fire_damage_percentage_value,
        if(fire_damage_percentage_value > 0, greatest(1, least(4, toUInt8(ceil((fire_damage_percentage_value / 22.0) * 4)))), 0) AS fire_damage_percentage_tier,
        if(fire_damage_percentage_value > 0, least(1., fire_damage_percentage_value / 22.0), 0.) AS fire_damage_percentage_quality_score,
        maxIf(mod_value, affix_key = 'tofireresistance') AS fire_resistance_value,
        if(fire_resistance_value > 0, greatest(1, least(8, toUInt8(ceil((fire_resistance_value / 48.0) * 8)))), 0) AS fire_resistance_tier,
        if(fire_resistance_value > 0, least(1., fire_resistance_value / 48.0), 0.) AS fire_resistance_quality_score,
        maxIf(mod_value, affix_key = 'toaccuracyrating') AS increased_accuracy_value,
        if(increased_accuracy_value > 0, greatest(1, least(14, toUInt8(ceil((increased_accuracy_value / 480.0) * 14)))), 0) AS increased_accuracy_tier,
        if(increased_accuracy_value > 0, least(1., increased_accuracy_value / 480.0), 0.) AS increased_accuracy_quality_score,
        maxIf(mod_value, affix_key = 'increasedattackspeed') AS increased_attack_speed_value,
        if(increased_attack_speed_value > 0, greatest(1, least(1, toUInt8(ceil((increased_attack_speed_value / 7.0) * 1)))), 0) AS increased_attack_speed_tier,
        if(increased_attack_speed_value > 0, least(1., increased_attack_speed_value / 7.0), 0.) AS increased_attack_speed_quality_score,
        maxIf(mod_value, affix_key = 'increasedcastspeed') AS increased_cast_speed_value,
        if(increased_cast_speed_value > 0, greatest(1, least(3, toUInt8(ceil((increased_cast_speed_value / 16.0) * 3)))), 0) AS increased_cast_speed_tier,
        if(increased_cast_speed_value > 0, least(1., increased_cast_speed_value / 16.0), 0.) AS increased_cast_speed_quality_score,
        maxIf(mod_value, affix_key = 'tomaximumenergyshield') AS increased_energy_shield_value,
        if(increased_energy_shield_value > 0, greatest(1, least(12, toUInt8(ceil((increased_energy_shield_value / 51.0) * 12)))), 0) AS increased_energy_shield_tier,
        if(increased_energy_shield_value > 0, least(1., increased_energy_shield_value / 51.0), 0.) AS increased_energy_shield_quality_score,
        maxIf(mod_value, affix_key = 'toevasionrating') AS increased_evasion_rating_value,
        if(increased_evasion_rating_value > 0, greatest(1, least(7, toUInt8(ceil((increased_evasion_rating_value / 170.0) * 7)))), 0) AS increased_evasion_rating_tier,
        if(increased_evasion_rating_value > 0, least(1., increased_evasion_rating_value / 170.0), 0.) AS increased_evasion_rating_quality_score,
        maxIf(mod_value, affix_key = 'tomaximumlife') AS increased_life_value,
        if(increased_life_value > 0, greatest(1, least(2, toUInt8(ceil((increased_life_value / 144.0) * 2)))), 0) AS increased_life_tier,
        if(increased_life_value > 0, least(1., increased_life_value / 144.0), 0.) AS increased_life_quality_score,
        maxIf(mod_value, affix_key = 'tomaximummana') AS increased_mana_value,
        if(increased_mana_value > 0, greatest(1, least(13, toUInt8(ceil((increased_mana_value / 78.0) * 13)))), 0) AS increased_mana_tier,
        if(increased_mana_value > 0, least(1., increased_mana_value / 78.0), 0.) AS increased_mana_quality_score,
        maxIf(mod_value, affix_key = 'increasedelementaldamagewithattackskills') AS increased_weapon_elemental_damage_percent_value,
        if(increased_weapon_elemental_damage_percent_value > 0, greatest(1, least(5, toUInt8(ceil((increased_weapon_elemental_damage_percent_value / 42.0) * 5)))), 0) AS increased_weapon_elemental_damage_percent_tier,
        if(increased_weapon_elemental_damage_percent_value > 0, least(1., increased_weapon_elemental_damage_percent_value / 42.0), 0.) AS increased_weapon_elemental_damage_percent_quality_score,
        maxIf(mod_value, affix_key = 'tointelligence') AS intelligence_value,
        if(intelligence_value > 0, greatest(1, least(9, toUInt8(ceil((intelligence_value / 55.0) * 9)))), 0) AS intelligence_tier,
        if(intelligence_value > 0, least(1., intelligence_value / 55.0), 0.) AS intelligence_quality_score,
        maxIf(mod_value, affix_key = 'increasedrarityofitemsfound') AS item_found_rarity_increase_value,
        if(item_found_rarity_increase_value > 0, greatest(1, least(8, toUInt8(ceil((item_found_rarity_increase_value / 28.0) * 8)))), 0) AS item_found_rarity_increase_tier,
        if(item_found_rarity_increase_value > 0, least(1., item_found_rarity_increase_value / 28.0), 0.) AS item_found_rarity_increase_quality_score,
        maxIf(mod_value, affix_key = 'gainlifeperenemyhitwithattacks') AS life_gain_per_target_value,
        if(life_gain_per_target_value > 0, greatest(1, least(1, toUInt8(ceil((life_gain_per_target_value / 2.0) * 1)))), 0) AS life_gain_per_target_tier,
        if(life_gain_per_target_value > 0, least(1., life_gain_per_target_value / 2.0), 0.) AS life_gain_per_target_quality_score,
        maxIf(mod_value, affix_key = 'gainlifeperenemykilled') AS life_gained_from_enemy_death_value,
        if(life_gained_from_enemy_death_value > 0, greatest(1, least(6, toUInt8(ceil((life_gained_from_enemy_death_value / 110.0) * 6)))), 0) AS life_gained_from_enemy_death_tier,
        if(life_gained_from_enemy_death_value > 0, least(1., life_gained_from_enemy_death_value / 110.0), 0.) AS life_gained_from_enemy_death_quality_score,
        maxIf(mod_value, affix_key = 'ofphysicalattackdamageleechedaslife') AS life_leech_value,
        if(life_leech_value > 0, greatest(1, least(1, toUInt8(ceil((life_leech_value / 0.4) * 1)))), 0) AS life_leech_tier,
        if(life_leech_value > 0, least(1., life_leech_value / 0.4), 0.) AS life_leech_quality_score,
        maxIf(mod_value, affix_key = 'regeneratelifepersecond') AS life_regeneration_value,
        if(life_regeneration_value > 0, greatest(1, least(2, toUInt8(ceil((life_regeneration_value / 128.0) * 2)))), 0) AS life_regeneration_tier,
        if(life_regeneration_value > 0, least(1., life_regeneration_value / 128.0), 0.) AS life_regeneration_quality_score,
        maxIf(mod_value, affix_key = 'increasedliferegenerationrate') AS life_regeneration_rate_value,
        if(life_regeneration_rate_value > 0, greatest(1, least(5, toUInt8(ceil((life_regeneration_rate_value / 21.0) * 5)))), 0) AS life_regeneration_rate_tier,
        if(life_regeneration_rate_value > 0, least(1., life_regeneration_rate_value / 21.0), 0.) AS life_regeneration_rate_quality_score,
        maxIf(mod_value, affix_key = 'increasedlightradiusincreasedglobalaccuracyrating') AS light_radius_increased_global_accuracy_rating_value,
        if(light_radius_increased_global_accuracy_rating_value > 0, greatest(1, least(3, toUInt8(ceil((light_radius_increased_global_accuracy_rating_value / 20.0) * 3)))), 0) AS light_radius_increased_global_accuracy_rating_tier,
        if(light_radius_increased_global_accuracy_rating_value > 0, least(1., light_radius_increased_global_accuracy_rating_value / 20.0), 0.) AS light_radius_increased_global_accuracy_rating_quality_score,
        maxIf(mod_value, affix_key = 'increasedlightradiustoaccuracyrating') AS light_radius_to_accuracy_rating_value,
        if(light_radius_to_accuracy_rating_value > 0, greatest(1, least(2, toUInt8(ceil((light_radius_to_accuracy_rating_value / 40.0) * 2)))), 0) AS light_radius_to_accuracy_rating_tier,
        if(light_radius_to_accuracy_rating_value > 0, least(1., light_radius_to_accuracy_rating_value / 40.0), 0.) AS light_radius_to_accuracy_rating_quality_score,
        maxIf(mod_value, affix_key = 'addstolightningdamagetoattacks') AS lightning_damage_value,
        if(lightning_damage_value > 0, greatest(1, least(9, toUInt8(ceil((lightning_damage_value / 72.0) * 9)))), 0) AS lightning_damage_tier,
        if(lightning_damage_value > 0, least(1., lightning_damage_value / 72.0), 0.) AS lightning_damage_quality_score,
        maxIf(mod_value, affix_key = 'increasedlightningdamage') AS lightning_damage_percentage_value,
        if(lightning_damage_percentage_value > 0, greatest(1, least(4, toUInt8(ceil((lightning_damage_percentage_value / 22.0) * 4)))), 0) AS lightning_damage_percentage_tier,
        if(lightning_damage_percentage_value > 0, least(1., lightning_damage_percentage_value / 22.0), 0.) AS lightning_damage_percentage_quality_score,
        maxIf(mod_value, affix_key = 'tolightningresistance') AS lightning_resistance_value,
        if(lightning_resistance_value > 0, greatest(1, least(8, toUInt8(ceil((lightning_resistance_value / 48.0) * 8)))), 0) AS lightning_resistance_tier,
        if(lightning_resistance_value > 0, least(1., lightning_resistance_value / 48.0), 0.) AS lightning_resistance_quality_score,
        maxIf(mod_value, affix_key = 'gainmanaperenemykilled') AS mana_gained_from_enemy_death_value,
        if(mana_gained_from_enemy_death_value > 0, greatest(1, least(6, toUInt8(ceil((mana_gained_from_enemy_death_value / 50.0) * 6)))), 0) AS mana_gained_from_enemy_death_tier,
        if(mana_gained_from_enemy_death_value > 0, least(1., mana_gained_from_enemy_death_value / 50.0), 0.) AS mana_gained_from_enemy_death_quality_score,
        maxIf(mod_value, affix_key = 'ofphysicalattackdamageleechedasmana') AS mana_leech_value,
        if(mana_leech_value > 0, greatest(1, least(1, toUInt8(ceil((mana_leech_value / 0.4) * 1)))), 0) AS mana_leech_tier,
        if(mana_leech_value > 0, least(1., mana_leech_value / 0.4), 0.) AS mana_leech_quality_score,
        maxIf(mod_value, affix_key = 'increasedmanaregenerationrate') AS mana_regeneration_value,
        if(mana_regeneration_value > 0, greatest(1, least(6, toUInt8(ceil((mana_regeneration_value / 69.0) * 6)))), 0) AS mana_regeneration_tier,
        if(mana_regeneration_value > 0, least(1., mana_regeneration_value / 69.0), 0.) AS mana_regeneration_quality_score,
        maxIf(mod_value, affix_key = 'addstophysicaldamagetoattacks') AS physical_damage_value,
        if(physical_damage_value > 0, greatest(1, least(9, toUInt8(ceil((physical_damage_value / 26.0) * 9)))), 0) AS physical_damage_tier,
        if(physical_damage_value > 0, least(1., physical_damage_value / 26.0), 0.) AS physical_damage_quality_score,
        maxIf(mod_value, affix_key = 'additionalphysicaldamagereduction') AS reduced_physical_damage_taken_value,
        if(reduced_physical_damage_taken_value > 0, greatest(1, least(5, toUInt8(ceil((reduced_physical_damage_taken_value / 8.0) * 5)))), 0) AS reduced_physical_damage_taken_tier,
        if(reduced_physical_damage_taken_value > 0, least(1., reduced_physical_damage_taken_value / 8.0), 0.) AS reduced_physical_damage_taken_quality_score,
        maxIf(mod_value, affix_key = 'tostrength') AS strength_value,
        if(strength_value > 0, greatest(1, least(9, toUInt8(ceil((strength_value / 55.0) * 9)))), 0) AS strength_tier,
        if(strength_value > 0, least(1., strength_value / 55.0), 0.) AS strength_quality_score,
        countIf(mod_value > 0) AS recognized_affix_count
    FROM (
        SELECT
            t.as_of_ts,
            t.item_id,
            t.identity_key,
            t.rarity,
            t.ilvl,
            t.corrupted,
            t.fractured,
            t.synthesised,
            t.support_count_recent,
            t.target_price_chaos,
            t.target_fast_sale_24h_price,
            t.target_sale_probability_24h,
            t.target_likely_sold,
            t.label_weight,
            arrayJoin(
                if(
                    empty(arrayConcat(
                        extractAll(explicit_blob, '"([^"]+)"'),
                        extractAll(implicit_blob, '"([^"]+)"'),
                        extractAll(crafted_blob, '"([^"]+)"'),
                        extractAll(fractured_blob, '"([^"]+)"'),
                        extractAll(enchant_blob, '"([^"]+)"')
                    )),
                    [''],
                    arrayConcat(
                        extractAll(explicit_blob, '"([^"]+)"'),
                        extractAll(implicit_blob, '"([^"]+)"'),
                        extractAll(crafted_blob, '"([^"]+)"'),
                        extractAll(fractured_blob, '"([^"]+)"'),
                        extractAll(enchant_blob, '"([^"]+)"')
                    )
                )
            ) AS mod_line,
            replaceRegexpAll(replaceRegexpAll(replaceRegexpAll(replaceAll(lowerUTF8(trimBoth(replaceAll(mod_line, '"', ''))), '\d+(?:\.\d+)?', '{N}'), '\{N\}', ''), '[^a-z]+', ''), '^$', '') AS affix_key,
            if(empty(extractAll(mod_line, '\d+(?:\.\d+)?')), 0., arrayReduce('max', arrayMap(x -> toFloat64OrZero(x), extractAll(mod_line, '\d+(?:\.\d+)?')))) AS mod_value,
            extract(o.affix_payload_json, '"explicit":\[(.*?)\],"implicit":') AS explicit_blob,
            extract(o.affix_payload_json, '"implicit":\[(.*?)\],"crafted":') AS implicit_blob,
            extract(o.affix_payload_json, '"crafted":\[(.*?)\],"fractured":') AS crafted_blob,
            extract(o.affix_payload_json, '"fractured":\[(.*?)\],"enchant":') AS fractured_blob,
            extract(o.affix_payload_json, '"enchant":\[(.*?)\]}') AS enchant_blob
        FROM poe_trade.ml_v3_training_examples AS t
        INNER JOIN poe_trade.silver_v3_item_observations AS o ON (o.league = t.league) AND (o.item_id = t.item_id) AND (o.observed_at = t.as_of_ts)
        WHERE (t.league = 'Mirage') AND (t.category = 'ring') AND (t.base_type = 'Iron Ring') AND (t.target_price_chaos > 0)
    ) AS raw_lines
    GROUP BY
        as_of_ts,
        item_id,
        identity_key,
        rarity,
        ilvl,
        corrupted,
        fractured,
        synthesised,
        support_count_recent,
        target_price_chaos,
        target_fast_sale_24h_price,
        target_sale_probability_24h,
        target_likely_sold,
        label_weight
) AS item_rows;
