CREATE VIEW IF NOT EXISTS poe_trade.v_ml_v3_mirage_iron_ring_wide AS
SELECT
    item_rows.item_id AS item_id,
    item_rows.item_name AS item_name,
    item_rows.base_type AS base_type,
    item_rows.ilvl AS ilvl,
    item_rows.corrupted AS corrupted,
    item_rows.fractured AS fractured,
    item_rows.synthesised AS synthesised,
    item_rows.mirrored AS mirrored,
    item_rows.quality AS quality,
    item_rows.number_of_sockets AS number_of_sockets,
    item_rows.number_of_red_sockets AS number_of_red_sockets,
    item_rows.number_of_green_sockets AS number_of_green_sockets,
    item_rows.number_of_blue_sockets AS number_of_blue_sockets,
    item_rows.number_of_white_sockets AS number_of_white_sockets,
    item_rows.number_of_links AS number_of_links,
    maxIf(item_rows.affix_value, item_rows.affix_name = 'Strength') AS strength_value,
    maxIf(item_rows.affix_tier, item_rows.affix_name = 'Strength') AS strength_tier,
    maxIf(item_rows.affix_quality_score, item_rows.affix_name = 'Strength') * 100.0 AS strength_quality_pct,
    maxIf(item_rows.affix_value, item_rows.affix_name = 'Dexterity') AS dexterity_value,
    maxIf(item_rows.affix_tier, item_rows.affix_name = 'Dexterity') AS dexterity_tier,
    maxIf(item_rows.affix_quality_score, item_rows.affix_name = 'Dexterity') * 100.0 AS dexterity_quality_pct,
    maxIf(item_rows.affix_value, item_rows.affix_name = 'Intelligence') AS intelligence_value,
    maxIf(item_rows.affix_tier, item_rows.affix_name = 'Intelligence') AS intelligence_tier,
    maxIf(item_rows.affix_quality_score, item_rows.affix_name = 'Intelligence') * 100.0 AS intelligence_quality_pct,
    maxIf(item_rows.affix_value, item_rows.affix_name = 'MaximumLife') AS maximum_life_value,
    maxIf(item_rows.affix_tier, item_rows.affix_name = 'MaximumLife') AS maximum_life_tier,
    maxIf(item_rows.affix_quality_score, item_rows.affix_name = 'MaximumLife') * 100.0 AS maximum_life_quality_pct,
    maxIf(item_rows.affix_value, item_rows.affix_name = 'MaximumMana') AS maximum_mana_value,
    maxIf(item_rows.affix_tier, item_rows.affix_name = 'MaximumMana') AS maximum_mana_tier,
    maxIf(item_rows.affix_quality_score, item_rows.affix_name = 'MaximumMana') * 100.0 AS maximum_mana_quality_pct,
    maxIf(item_rows.affix_value, item_rows.affix_name = 'MaximumEnergyShield') AS maximum_energy_shield_value,
    maxIf(item_rows.affix_tier, item_rows.affix_name = 'MaximumEnergyShield') AS maximum_energy_shield_tier,
    maxIf(item_rows.affix_quality_score, item_rows.affix_name = 'MaximumEnergyShield') * 100.0 AS maximum_energy_shield_quality_pct,
    maxIf(item_rows.affix_value, item_rows.affix_name = 'EvasionRating') AS evasion_rating_value,
    maxIf(item_rows.affix_tier, item_rows.affix_name = 'EvasionRating') AS evasion_rating_tier,
    maxIf(item_rows.affix_quality_score, item_rows.affix_name = 'EvasionRating') * 100.0 AS evasion_rating_quality_pct,
    maxIf(item_rows.affix_value, item_rows.affix_name = 'Armor') AS armor_value,
    maxIf(item_rows.affix_tier, item_rows.affix_name = 'Armor') AS armor_tier,
    maxIf(item_rows.affix_quality_score, item_rows.affix_name = 'Armor') * 100.0 AS armor_quality_pct,
    maxIf(item_rows.affix_value, item_rows.affix_name = 'MovementSpeed') AS movement_speed_value,
    maxIf(item_rows.affix_tier, item_rows.affix_name = 'MovementSpeed') AS movement_speed_tier,
    maxIf(item_rows.affix_quality_score, item_rows.affix_name = 'MovementSpeed') * 100.0 AS movement_speed_quality_pct,
    maxIf(item_rows.affix_value, item_rows.affix_name = 'CriticalStrikeChance') AS critical_strike_chance_value,
    maxIf(item_rows.affix_tier, item_rows.affix_name = 'CriticalStrikeChance') AS critical_strike_chance_tier,
    maxIf(item_rows.affix_quality_score, item_rows.affix_name = 'CriticalStrikeChance') * 100.0 AS critical_strike_chance_quality_pct,
    maxIf(item_rows.affix_value, item_rows.affix_name = 'CriticalStrikeMultiplier') AS critical_strike_multiplier_value,
    maxIf(item_rows.affix_tier, item_rows.affix_name = 'CriticalStrikeMultiplier') AS critical_strike_multiplier_tier,
    maxIf(item_rows.affix_quality_score, item_rows.affix_name = 'CriticalStrikeMultiplier') * 100.0 AS critical_strike_multiplier_quality_pct,
    maxIf(item_rows.affix_value, item_rows.affix_name = 'AttackSpeed') AS attack_speed_value,
    maxIf(item_rows.affix_tier, item_rows.affix_name = 'AttackSpeed') AS attack_speed_tier,
    maxIf(item_rows.affix_quality_score, item_rows.affix_name = 'AttackSpeed') * 100.0 AS attack_speed_quality_pct,
    maxIf(item_rows.affix_value, item_rows.affix_name = 'CastSpeed') AS cast_speed_value,
    maxIf(item_rows.affix_tier, item_rows.affix_name = 'CastSpeed') AS cast_speed_tier,
    maxIf(item_rows.affix_quality_score, item_rows.affix_name = 'CastSpeed') * 100.0 AS cast_speed_quality_pct,
    maxIf(item_rows.affix_value, item_rows.affix_name = 'PhysicalDamage') AS physical_damage_value,
    maxIf(item_rows.affix_tier, item_rows.affix_name = 'PhysicalDamage') AS physical_damage_tier,
    maxIf(item_rows.affix_quality_score, item_rows.affix_name = 'PhysicalDamage') * 100.0 AS physical_damage_quality_pct,
    maxIf(item_rows.affix_value, item_rows.affix_name = 'FireDamage') AS fire_damage_value,
    maxIf(item_rows.affix_tier, item_rows.affix_name = 'FireDamage') AS fire_damage_tier,
    maxIf(item_rows.affix_quality_score, item_rows.affix_name = 'FireDamage') * 100.0 AS fire_damage_quality_pct,
    maxIf(item_rows.affix_value, item_rows.affix_name = 'ColdDamage') AS cold_damage_value,
    maxIf(item_rows.affix_tier, item_rows.affix_name = 'ColdDamage') AS cold_damage_tier,
    maxIf(item_rows.affix_quality_score, item_rows.affix_name = 'ColdDamage') * 100.0 AS cold_damage_quality_pct,
    maxIf(item_rows.affix_value, item_rows.affix_name = 'LightningDamage') AS lightning_damage_value,
    maxIf(item_rows.affix_tier, item_rows.affix_name = 'LightningDamage') AS lightning_damage_tier,
    maxIf(item_rows.affix_quality_score, item_rows.affix_name = 'LightningDamage') * 100.0 AS lightning_damage_quality_pct,
    maxIf(item_rows.affix_value, item_rows.affix_name = 'ChaosDamage') AS chaos_damage_value,
    maxIf(item_rows.affix_tier, item_rows.affix_name = 'ChaosDamage') AS chaos_damage_tier,
    maxIf(item_rows.affix_quality_score, item_rows.affix_name = 'ChaosDamage') * 100.0 AS chaos_damage_quality_pct,
    maxIf(item_rows.affix_value, item_rows.affix_name = 'ElementalDamage') AS elemental_damage_value,
    maxIf(item_rows.affix_tier, item_rows.affix_name = 'ElementalDamage') AS elemental_damage_tier,
    maxIf(item_rows.affix_quality_score, item_rows.affix_name = 'ElementalDamage') * 100.0 AS elemental_damage_quality_pct,
    maxIf(item_rows.affix_value, item_rows.affix_name = 'SpellDamage') AS spell_damage_value,
    maxIf(item_rows.affix_tier, item_rows.affix_name = 'SpellDamage') AS spell_damage_tier,
    maxIf(item_rows.affix_quality_score, item_rows.affix_name = 'SpellDamage') * 100.0 AS spell_damage_quality_pct,
    maxIf(item_rows.affix_value, item_rows.affix_name = 'FireResistance') AS fire_resistance_value,
    maxIf(item_rows.affix_tier, item_rows.affix_name = 'FireResistance') AS fire_resistance_tier,
    maxIf(item_rows.affix_quality_score, item_rows.affix_name = 'FireResistance') * 100.0 AS fire_resistance_quality_pct,
    maxIf(item_rows.affix_value, item_rows.affix_name = 'ColdResistance') AS cold_resistance_value,
    maxIf(item_rows.affix_tier, item_rows.affix_name = 'ColdResistance') AS cold_resistance_tier,
    maxIf(item_rows.affix_quality_score, item_rows.affix_name = 'ColdResistance') * 100.0 AS cold_resistance_quality_pct,
    maxIf(item_rows.affix_value, item_rows.affix_name = 'LightningResistance') AS lightning_resistance_value,
    maxIf(item_rows.affix_tier, item_rows.affix_name = 'LightningResistance') AS lightning_resistance_tier,
    maxIf(item_rows.affix_quality_score, item_rows.affix_name = 'LightningResistance') * 100.0 AS lightning_resistance_quality_pct,
    maxIf(item_rows.affix_value, item_rows.affix_name = 'ChaosResistance') AS chaos_resistance_value,
    maxIf(item_rows.affix_tier, item_rows.affix_name = 'ChaosResistance') AS chaos_resistance_tier,
    maxIf(item_rows.affix_quality_score, item_rows.affix_name = 'ChaosResistance') * 100.0 AS chaos_resistance_quality_pct,
    maxIf(item_rows.affix_value, item_rows.affix_name = 'AllElementalResistances') AS all_elemental_resistances_value,
    maxIf(item_rows.affix_tier, item_rows.affix_name = 'AllElementalResistances') AS all_elemental_resistances_tier,
    maxIf(item_rows.affix_quality_score, item_rows.affix_name = 'AllElementalResistances') * 100.0 AS all_elemental_resistances_quality_pct,
    item_rows.observed_at AS observed_at
FROM
(
    SELECT
        base.as_of_ts AS observed_at,
        base.item_id AS item_id,
        base.item_name AS item_name,
        base.base_type AS base_type,
        base.ilvl AS ilvl,
        base.corrupted AS corrupted,
        base.fractured AS fractured,
        base.synthesised AS synthesised,
        toUInt8(ifNull(JSONExtractBool(obs.item_json, 'mirrored'), 0)) AS mirrored,
        toUInt8(greatest(0, JSONExtractInt(obs.item_json, 'quality'))) AS quality,
        JSONExtractArrayRaw(obs.item_json, 'sockets') AS sockets_json,
        arrayMap(socket -> toUInt8(JSONExtractUInt(socket, 'group')), sockets_json) AS socket_groups,
        length(sockets_json) AS number_of_sockets,
        arrayCount(socket -> JSONExtractString(socket, 'sColour') = 'R', sockets_json) AS number_of_red_sockets,
        arrayCount(socket -> JSONExtractString(socket, 'sColour') = 'G', sockets_json) AS number_of_green_sockets,
        arrayCount(socket -> JSONExtractString(socket, 'sColour') = 'B', sockets_json) AS number_of_blue_sockets,
        arrayCount(socket -> JSONExtractString(socket, 'sColour') = 'W', sockets_json) AS number_of_white_sockets,
        if(
            empty(socket_groups),
            0,
            arrayMax(
                arrayMap(
                    group_id -> countEqual(socket_groups, group_id),
                    arrayDistinct(socket_groups)
                )
            )
        ) AS number_of_links,
        base.affix_name AS affix_name,
        base.affix_value AS affix_value,
        base.affix_tier AS affix_tier,
        base.affix_quality_score AS affix_quality_score
    FROM poe_trade.v_ml_v3_iron_ring_affix_flattened_poc AS base
    INNER JOIN poe_trade.silver_v3_item_observations AS obs
        ON obs.league = base.league
        AND obs.observed_at = base.as_of_ts
        AND ifNull(obs.item_id, concat(obs.stash_id, '|', obs.base_type, '|', toString(obs.observed_at))) = base.item_key
) AS item_rows
GROUP BY
    item_rows.item_id,
    item_rows.item_name,
    item_rows.base_type,
    item_rows.ilvl,
    item_rows.corrupted,
    item_rows.fractured,
    item_rows.synthesised,
    item_rows.mirrored,
    item_rows.quality,
    item_rows.number_of_sockets,
    item_rows.number_of_red_sockets,
    item_rows.number_of_green_sockets,
    item_rows.number_of_blue_sockets,
    item_rows.number_of_white_sockets,
    item_rows.number_of_links,
    item_rows.observed_at;
