-- Migration 0076: exhaustive Mirage Iron Ring ring-affix catalog
-- Generated from https://repoe-fork.github.io/mods.min.json

CREATE TABLE IF NOT EXISTS poe_trade.ml_ring_mod_catalog_v1 (
    mod_id String,
    mod_text_pattern String,
    mod_base_name String,
    mod_tier UInt8,
    mod_max_tier UInt8,
    mod_max_value Float64,
    mod_generation_type LowCardinality(String),
    required_level UInt16,
    ring_weight UInt32,
    updated_at DateTime64(3, 'UTC')
) ENGINE = ReplacingMergeTree(updated_at)
ORDER BY (mod_base_name, mod_tier, mod_id)
SETTINGS index_granularity = 8192;

TRUNCATE TABLE poe_trade.ml_ring_mod_catalog_v1;

INSERT INTO poe_trade.ml_ring_mod_catalog_v1 (
    mod_id,
    mod_text_pattern,
    mod_base_name,
    mod_tier,
    mod_max_tier,
    mod_max_value,
    mod_generation_type,
    required_level,
    ring_weight,
    updated_at
) VALUES
    ('AddedColdDamage1', 'Adds {N} to {N} Cold Damage to Attacks', 'AddedColdDamage', 1, 9, 2.00, 'prefix', 2, 500, now64(3)),
    ('AddedColdDamage2', 'Adds ({N}-{N}) to ({N}-{N}) Cold Damage to Attacks', 'AddedColdDamage', 2, 9, 8.00, 'prefix', 13, 500, now64(3)),
    ('AddedColdDamage3', 'Adds ({N}-{N}) to ({N}-{N}) Cold Damage to Attacks', 'AddedColdDamage', 3, 9, 12.00, 'prefix', 21, 500, now64(3)),
    ('AddedColdDamage4', 'Adds ({N}-{N}) to ({N}-{N}) Cold Damage to Attacks', 'AddedColdDamage', 4, 9, 16.00, 'prefix', 29, 500, now64(3)),
    ('AddedColdDamage5', 'Adds ({N}-{N}) to ({N}-{N}) Cold Damage to Attacks', 'AddedColdDamage', 5, 9, 19.00, 'prefix', 36, 500, now64(3)),
    ('AddedColdDamage6', 'Adds ({N}-{N}) to ({N}-{N}) Cold Damage to Attacks', 'AddedColdDamage', 6, 9, 24.00, 'prefix', 45, 500, now64(3)),
    ('AddedColdDamage7', 'Adds ({N}-{N}) to ({N}-{N}) Cold Damage to Attacks', 'AddedColdDamage', 7, 9, 28.00, 'prefix', 53, 100, now64(3)),
    ('AddedColdDamage8', 'Adds ({N}-{N}) to ({N}-{N}) Cold Damage to Attacks', 'AddedColdDamage', 8, 9, 34.00, 'prefix', 65, 100, now64(3)),
    ('AddedColdDamage9', 'Adds ({N}-{N}) to ({N}-{N}) Cold Damage to Attacks', 'AddedColdDamage', 9, 9, 40.00, 'prefix', 77, 50, now64(3)),
    ('AddedFireDamage1', 'Adds {N} to {N} Fire Damage to Attacks', 'AddedFireDamage', 1, 9, 2.00, 'prefix', 1, 500, now64(3)),
    ('AddedFireDamage2', 'Adds ({N}-{N}) to ({N}-{N}) Fire Damage to Attacks', 'AddedFireDamage', 2, 9, 8.00, 'prefix', 12, 500, now64(3)),
    ('AddedFireDamage3', 'Adds ({N}-{N}) to ({N}-{N}) Fire Damage to Attacks', 'AddedFireDamage', 3, 9, 13.00, 'prefix', 20, 500, now64(3)),
    ('AddedFireDamage4', 'Adds ({N}-{N}) to ({N}-{N}) Fire Damage to Attacks', 'AddedFireDamage', 4, 9, 18.00, 'prefix', 28, 500, now64(3)),
    ('AddedFireDamage5', 'Adds ({N}-{N}) to ({N}-{N}) Fire Damage to Attacks', 'AddedFireDamage', 5, 9, 22.00, 'prefix', 35, 500, now64(3)),
    ('AddedFireDamage6', 'Adds ({N}-{N}) to ({N}-{N}) Fire Damage to Attacks', 'AddedFireDamage', 6, 9, 27.00, 'prefix', 44, 500, now64(3)),
    ('AddedFireDamage7', 'Adds ({N}-{N}) to ({N}-{N}) Fire Damage to Attacks', 'AddedFireDamage', 7, 9, 31.00, 'prefix', 52, 100, now64(3)),
    ('AddedFireDamage8', 'Adds ({N}-{N}) to ({N}-{N}) Fire Damage to Attacks', 'AddedFireDamage', 8, 9, 38.00, 'prefix', 64, 100, now64(3)),
    ('AddedFireDamage9', 'Adds ({N}-{N}) to ({N}-{N}) Fire Damage to Attacks', 'AddedFireDamage', 9, 9, 45.00, 'prefix', 76, 50, now64(3)),
    ('AddedLightningDamage1', 'Adds {N} to {N} Lightning Damage to Attacks', 'AddedLightningDamage', 1, 9, 5.00, 'prefix', 3, 500, now64(3)),
    ('AddedLightningDamage2', 'Adds {N} to ({N}-{N}) Lightning Damage to Attacks', 'AddedLightningDamage', 2, 9, 15.00, 'prefix', 13, 500, now64(3)),
    ('AddedLightningDamage3', 'Adds ({N}-{N}) to ({N}-{N}) Lightning Damage to Attacks', 'AddedLightningDamage', 3, 9, 23.00, 'prefix', 22, 500, now64(3)),
    ('AddedLightningDamage4', 'Adds ({N}-{N}) to ({N}-{N}) Lightning Damage to Attacks', 'AddedLightningDamage', 4, 9, 28.00, 'prefix', 28, 500, now64(3)),
    ('AddedLightningDamage5', 'Adds ({N}-{N}) to ({N}-{N}) Lightning Damage to Attacks', 'AddedLightningDamage', 5, 9, 34.00, 'prefix', 35, 500, now64(3)),
    ('AddedLightningDamage6', 'Adds ({N}-{N}) to ({N}-{N}) Lightning Damage to Attacks', 'AddedLightningDamage', 6, 9, 43.00, 'prefix', 44, 500, now64(3)),
    ('AddedLightningDamage7', 'Adds ({N}-{N}) to ({N}-{N}) Lightning Damage to Attacks', 'AddedLightningDamage', 7, 9, 50.00, 'prefix', 52, 100, now64(3)),
    ('AddedLightningDamage8', 'Adds ({N}-{N}) to ({N}-{N}) Lightning Damage to Attacks', 'AddedLightningDamage', 8, 9, 61.00, 'prefix', 64, 100, now64(3)),
    ('AddedLightningDamage9', 'Adds ({N}-{N}) to ({N}-{N}) Lightning Damage to Attacks', 'AddedLightningDamage', 9, 9, 72.00, 'prefix', 76, 50, now64(3)),
    ('AddedPhysicalDamage1', 'Adds {N} to {N} Physical Damage to Attacks', 'AddedPhysicalDamage', 1, 6, 2.00, 'prefix', 5, 1000, now64(3)),
    ('AddedPhysicalDamage2', 'Adds ({N}-{N}) to ({N}-{N}) Physical Damage to Attacks', 'AddedPhysicalDamage', 2, 6, 5.00, 'prefix', 13, 1000, now64(3)),
    ('AddedPhysicalDamage3', 'Adds ({N}-{N}) to ({N}-{N}) Physical Damage to Attacks', 'AddedPhysicalDamage', 3, 6, 7.00, 'prefix', 19, 1000, now64(3)),
    ('AddedPhysicalDamage4', 'Adds ({N}-{N}) to ({N}-{N}) Physical Damage to Attacks', 'AddedPhysicalDamage', 4, 6, 10.00, 'prefix', 28, 1000, now64(3)),
    ('AddedPhysicalDamage5', 'Adds ({N}-{N}) to ({N}-{N}) Physical Damage to Attacks', 'AddedPhysicalDamage', 5, 6, 12.00, 'prefix', 35, 1000, now64(3)),
    ('AddedPhysicalDamage6', 'Adds ({N}-{N}) to ({N}-{N}) Physical Damage to Attacks', 'AddedPhysicalDamage', 6, 6, 15.00, 'prefix', 44, 1000, now64(3)),
    ('AllAttributes1', '+({N}-{N}) to all Attributes', 'AllAttributes', 1, 4, 4.00, 'suffix', 1, 400, now64(3)),
    ('AllAttributes2', '+({N}-{N}) to all Attributes', 'AllAttributes', 2, 4, 8.00, 'suffix', 11, 400, now64(3)),
    ('AllAttributes3', '+({N}-{N}) to all Attributes', 'AllAttributes', 3, 4, 12.00, 'suffix', 22, 400, now64(3)),
    ('AllAttributes4', '+({N}-{N}) to all Attributes', 'AllAttributes', 4, 4, 16.00, 'suffix', 33, 400, now64(3)),
    ('AllResistances1', '+({N}-{N})% to all Elemental Resistances', 'AllResistances', 1, 5, 5.00, 'suffix', 12, 1000, now64(3)),
    ('AllResistances2', '+({N}-{N})% to all Elemental Resistances', 'AllResistances', 2, 5, 8.00, 'suffix', 24, 1000, now64(3)),
    ('AllResistances3', '+({N}-{N})% to all Elemental Resistances', 'AllResistances', 3, 5, 11.00, 'suffix', 36, 1000, now64(3)),
    ('AllResistances4', '+({N}-{N})% to all Elemental Resistances', 'AllResistances', 4, 5, 14.00, 'suffix', 48, 1000, now64(3)),
    ('AllResistances5', '+({N}-{N})% to all Elemental Resistances', 'AllResistances', 5, 5, 16.00, 'suffix', 60, 1000, now64(3)),
    ('ChaosResist1', '+({N}-{N})% to Chaos Resistance', 'ChaosResist', 1, 6, 10.00, 'suffix', 16, 250, now64(3)),
    ('ChaosResist2', '+({N}-{N})% to Chaos Resistance', 'ChaosResist', 2, 6, 15.00, 'suffix', 30, 250, now64(3)),
    ('ChaosResist3', '+({N}-{N})% to Chaos Resistance', 'ChaosResist', 3, 6, 20.00, 'suffix', 44, 250, now64(3)),
    ('ChaosResist4', '+({N}-{N})% to Chaos Resistance', 'ChaosResist', 4, 6, 25.00, 'suffix', 56, 250, now64(3)),
    ('ChaosResist5', '+({N}-{N})% to Chaos Resistance', 'ChaosResist', 5, 6, 30.00, 'suffix', 65, 250, now64(3)),
    ('ChaosResist6', '+({N}-{N})% to Chaos Resistance', 'ChaosResist', 6, 6, 35.00, 'suffix', 81, 250, now64(3)),
    ('ColdDamagePercent1', '({N}-{N})% increased Cold Damage', 'ColdDamagePercent', 1, 4, 12.00, 'suffix', 12, 500, now64(3)),
    ('ColdDamagePercent2', '({N}-{N})% increased Cold Damage', 'ColdDamagePercent', 2, 4, 15.00, 'suffix', 24, 500, now64(3)),
    ('ColdDamagePercent3', '({N}-{N})% increased Cold Damage', 'ColdDamagePercent', 3, 4, 18.00, 'suffix', 36, 500, now64(3)),
    ('ColdDamagePercent4', '({N}-{N})% increased Cold Damage', 'ColdDamagePercent', 4, 4, 22.00, 'suffix', 50, 500, now64(3)),
    ('ColdResist1', '+({N}-{N})% to Cold Resistance', 'ColdResist', 1, 8, 11.00, 'suffix', 1, 1000, now64(3)),
    ('ColdResist2', '+({N}-{N})% to Cold Resistance', 'ColdResist', 2, 8, 17.00, 'suffix', 14, 1000, now64(3)),
    ('ColdResist3', '+({N}-{N})% to Cold Resistance', 'ColdResist', 3, 8, 23.00, 'suffix', 26, 1000, now64(3)),
    ('ColdResist4', '+({N}-{N})% to Cold Resistance', 'ColdResist', 4, 8, 29.00, 'suffix', 38, 1000, now64(3)),
    ('ColdResist5', '+({N}-{N})% to Cold Resistance', 'ColdResist', 5, 8, 35.00, 'suffix', 50, 1000, now64(3)),
    ('ColdResist6', '+({N}-{N})% to Cold Resistance', 'ColdResist', 6, 8, 41.00, 'suffix', 60, 1000, now64(3)),
    ('ColdResist7', '+({N}-{N})% to Cold Resistance', 'ColdResist', 7, 8, 45.00, 'suffix', 72, 1000, now64(3)),
    ('ColdResist8', '+({N}-{N})% to Cold Resistance', 'ColdResist', 8, 8, 48.00, 'suffix', 84, 1000, now64(3)),
    ('DamageTakenGainedAsLife1___', '({N}-{N})% of Damage taken Recouped as Life', 'DamageTakenGainedAsLife', 1, 3, 6.00, 'suffix', 44, 500, now64(3)),
    ('DamageTakenGainedAsLife4_', '({N}-{N})% of Damage taken Recouped as Life', 'DamageTakenGainedAsLife', 1, 3, 15.00, 'suffix', 79, 500, now64(3)),
    ('DamageTakenGainedAsLife2', '({N}-{N})% of Damage taken Recouped as Life', 'DamageTakenGainedAsLife', 2, 3, 9.00, 'suffix', 56, 500, now64(3)),
    ('DamageTakenGainedAsLife3', '({N}-{N})% of Damage taken Recouped as Life', 'DamageTakenGainedAsLife', 3, 3, 12.00, 'suffix', 68, 500, now64(3)),
    ('Dexterity1', '+({N}-{N}) to Dexterity', 'Dexterity', 1, 9, 12.00, 'suffix', 1, 1000, now64(3)),
    ('Dexterity2', '+({N}-{N}) to Dexterity', 'Dexterity', 2, 9, 17.00, 'suffix', 11, 1000, now64(3)),
    ('Dexterity3', '+({N}-{N}) to Dexterity', 'Dexterity', 3, 9, 22.00, 'suffix', 22, 1000, now64(3)),
    ('Dexterity4', '+({N}-{N}) to Dexterity', 'Dexterity', 4, 9, 27.00, 'suffix', 33, 1000, now64(3)),
    ('Dexterity5', '+({N}-{N}) to Dexterity', 'Dexterity', 5, 9, 32.00, 'suffix', 44, 1000, now64(3)),
    ('Dexterity6', '+({N}-{N}) to Dexterity', 'Dexterity', 6, 9, 37.00, 'suffix', 55, 1000, now64(3)),
    ('Dexterity7', '+({N}-{N}) to Dexterity', 'Dexterity', 7, 9, 42.00, 'suffix', 66, 1000, now64(3)),
    ('Dexterity8', '+({N}-{N}) to Dexterity', 'Dexterity', 8, 9, 50.00, 'suffix', 74, 1000, now64(3)),
    ('Dexterity9', '+({N}-{N}) to Dexterity', 'Dexterity', 9, 9, 55.00, 'suffix', 82, 1000, now64(3)),
    ('FireDamagePercent1', '({N}-{N})% increased Fire Damage', 'FireDamagePercent', 1, 4, 12.00, 'suffix', 8, 500, now64(3)),
    ('FireDamagePercent2', '({N}-{N})% increased Fire Damage', 'FireDamagePercent', 2, 4, 15.00, 'suffix', 22, 500, now64(3)),
    ('FireDamagePercent3', '({N}-{N})% increased Fire Damage', 'FireDamagePercent', 3, 4, 18.00, 'suffix', 36, 500, now64(3)),
    ('FireDamagePercent4', '({N}-{N})% increased Fire Damage', 'FireDamagePercent', 4, 4, 22.00, 'suffix', 50, 500, now64(3)),
    ('FireResist1', '+({N}-{N})% to Fire Resistance', 'FireResist', 1, 8, 11.00, 'suffix', 1, 1000, now64(3)),
    ('FireResist2', '+({N}-{N})% to Fire Resistance', 'FireResist', 2, 8, 17.00, 'suffix', 12, 1000, now64(3)),
    ('FireResist3', '+({N}-{N})% to Fire Resistance', 'FireResist', 3, 8, 23.00, 'suffix', 24, 1000, now64(3)),
    ('FireResist4', '+({N}-{N})% to Fire Resistance', 'FireResist', 4, 8, 29.00, 'suffix', 36, 1000, now64(3)),
    ('FireResist5', '+({N}-{N})% to Fire Resistance', 'FireResist', 5, 8, 35.00, 'suffix', 48, 1000, now64(3)),
    ('FireResist6', '+({N}-{N})% to Fire Resistance', 'FireResist', 6, 8, 41.00, 'suffix', 60, 1000, now64(3)),
    ('FireResist7', '+({N}-{N})% to Fire Resistance', 'FireResist', 7, 8, 45.00, 'suffix', 72, 1000, now64(3)),
    ('FireResist8', '+({N}-{N})% to Fire Resistance', 'FireResist', 8, 8, 48.00, 'suffix', 84, 1000, now64(3)),
    ('HellscapeDownsideCannotGainCharges', 'Cannot gain Charges', 'HellscapeDownsideCannotGainCharges', 1, 1, 1.00, 'scourge_detriment', 68, 500, now64(3)),
    ('HellscapeDownsideManaRegeneration0', '({N}-{N})% reduced Mana Regeneration Rate', 'HellscapeDownsideManaRegeneration', 0, 3, -16.00, 'scourge_detriment', 1, 1000, now64(3)),
    ('HellscapeDownsideManaRegeneration1', '({N}-{N})% reduced Mana Regeneration Rate', 'HellscapeDownsideManaRegeneration', 1, 3, -21.00, 'scourge_detriment', 1, 1000, now64(3)),
    ('HellscapeDownsideManaRegeneration2__', '({N}-{N})% reduced Mana Regeneration Rate', 'HellscapeDownsideManaRegeneration', 1, 3, -26.00, 'scourge_detriment', 45, 1000, now64(3)),
    ('HellscapeDownsideManaRegeneration3', '({N}-{N})% reduced Mana Regeneration Rate', 'HellscapeDownsideManaRegeneration', 3, 3, -36.00, 'scourge_detriment', 68, 1000, now64(3)),
    ('HellscapeDownsideManaRegeneration2b', '({N}-{N})% reduced Mana Regeneration Rate', 'HellscapeDownsideManaRegeneration2b', 1, 1, -31.00, 'scourge_detriment', 55, 500, now64(3)),
    ('HellscapeDownsideManaRegeneration3b', '({N}-{N})% reduced Mana Regeneration Rate', 'HellscapeDownsideManaRegeneration3b', 1, 1, -46.00, 'scourge_detriment', 68, 500, now64(3)),
    ('HellscapeDownsideMaximumEnduranceCharges1', '-{N} to Maximum Endurance Charges', 'HellscapeDownsideMaximumEnduranceCharges', 1, 1, -1.00, 'scourge_detriment', 68, 500, now64(3)),
    ('HellscapeDownsideMaximumFrenzyCharges1', '-{N} to Maximum Frenzy Charges', 'HellscapeDownsideMaximumFrenzyCharges', 1, 1, -1.00, 'scourge_detriment', 68, 500, now64(3)),
    ('HellscapeDownsideMaximumPowerCharges1', '-{N} to Maximum Power Charges', 'HellscapeDownsideMaximumPowerCharges', 1, 1, -1.00, 'scourge_detriment', 68, 500, now64(3)),
    ('HellscapeDownsideMinusMaximumLife0', '-({N}-{N}) to maximum Life', 'HellscapeDownsideMinusMaximumLife', 0, 2, -16.00, 'scourge_detriment', 1, 1000, now64(3)),
    ('HellscapeDownsideMinusMaximumLife1_', '-({N}-{N}) to maximum Life', 'HellscapeDownsideMinusMaximumLife', 1, 2, -21.00, 'scourge_detriment', 1, 1000, now64(3)),
    ('HellscapeDownsideMinusMaximumLife3_', '-({N}-{N}) to maximum Life', 'HellscapeDownsideMinusMaximumLife', 1, 2, -31.00, 'scourge_detriment', 68, 1000, now64(3)),
    ('HellscapeDownsideMinusMaximumLife2', '-({N}-{N}) to maximum Life', 'HellscapeDownsideMinusMaximumLife', 2, 2, -26.00, 'scourge_detriment', 45, 1000, now64(3)),
    ('HellscapeDownsideMinusMaximumMana0_', '-({N}-{N}) to maximum Mana', 'HellscapeDownsideMinusMaximumMana', 1, 1, -21.00, 'scourge_detriment', 1, 1000, now64(3)),
    ('HellscapeDownsideMinusMaximumMana1', '-({N}-{N}) to maximum Mana', 'HellscapeDownsideMinusMaximumMana', 1, 1, -26.00, 'scourge_detriment', 1, 1000, now64(3)),
    ('HellscapeDownsideMinusMaximumMana2__', '-({N}-{N}) to maximum Mana', 'HellscapeDownsideMinusMaximumMana', 1, 1, -31.00, 'scourge_detriment', 45, 1000, now64(3)),
    ('HellscapeDownsideMinusMaximumMana3_', '-({N}-{N}) to maximum Mana', 'HellscapeDownsideMinusMaximumMana', 1, 1, -36.00, 'scourge_detriment', 68, 1000, now64(3)),
    ('HellscapeDownsideRarityOfItemsFound0', '({N}-{N})% reduced Rarity of Items found', 'HellscapeDownsideRarityOfItemsFound', 0, 3, -18.00, 'scourge_detriment', 1, 1000, now64(3)),
    ('HellscapeDownsideRarityOfItemsFound1_', '({N}-{N})% reduced Rarity of Items found', 'HellscapeDownsideRarityOfItemsFound', 1, 3, -24.00, 'scourge_detriment', 1, 1000, now64(3)),
    ('HellscapeDownsideRarityOfItemsFound2', '({N}-{N})% reduced Rarity of Items found', 'HellscapeDownsideRarityOfItemsFound', 2, 3, -30.00, 'scourge_detriment', 45, 1000, now64(3)),
    ('HellscapeDownsideRarityOfItemsFound3', '({N}-{N})% reduced Rarity of Items found', 'HellscapeDownsideRarityOfItemsFound', 3, 3, -36.00, 'scourge_detriment', 68, 1000, now64(3)),
    ('HellscapeDownsideReducedChaosResistance0_', '-({N}-{N})% to Chaos Resistance', 'HellscapeDownsideReducedChaosResistance', 1, 1, -10.00, 'scourge_detriment', 16, 500, now64(3)),
    ('HellscapeDownsideReducedChaosResistance1', '-({N}-{N})% to Chaos Resistance', 'HellscapeDownsideReducedChaosResistance', 1, 1, -14.00, 'scourge_detriment', 16, 500, now64(3)),
    ('HellscapeDownsideReducedChaosResistance2_', '-({N}-{N})% to Chaos Resistance', 'HellscapeDownsideReducedChaosResistance', 1, 1, -18.00, 'scourge_detriment', 45, 750, now64(3)),
    ('HellscapeDownsideReducedChaosResistance3___', '-({N}-{N})% to Chaos Resistance', 'HellscapeDownsideReducedChaosResistance', 1, 1, -22.00, 'scourge_detriment', 68, 1000, now64(3)),
    ('HellscapeDownsideReducedColdResistance0', '-({N}-{N})% to Cold Resistance', 'HellscapeDownsideReducedColdResistance', 0, 3, -11.00, 'scourge_detriment', 1, 500, now64(3)),
    ('HellscapeDownsideReducedColdResistance1', '-({N}-{N})% to Cold Resistance', 'HellscapeDownsideReducedColdResistance', 1, 3, -16.00, 'scourge_detriment', 1, 500, now64(3)),
    ('HellscapeDownsideReducedColdResistance2', '-({N}-{N})% to Cold Resistance', 'HellscapeDownsideReducedColdResistance', 2, 3, -21.00, 'scourge_detriment', 45, 750, now64(3)),
    ('HellscapeDownsideReducedColdResistance3', '-({N}-{N})% to Cold Resistance', 'HellscapeDownsideReducedColdResistance', 3, 3, -26.00, 'scourge_detriment', 68, 1000, now64(3)),
    ('HellscapeDownsideReducedElementalResistances0_', '-{N}% to all Elemental Resistances', 'HellscapeDownsideReducedElementalResistances', 1, 1, -5.00, 'scourge_detriment', 1, 500, now64(3)),
    ('HellscapeDownsideReducedElementalResistances1_', '-({N}-{N})% to all Elemental Resistances', 'HellscapeDownsideReducedElementalResistances', 1, 1, -6.00, 'scourge_detriment', 1, 500, now64(3)),
    ('HellscapeDownsideReducedElementalResistances2_', '-({N}-{N})% to all Elemental Resistances', 'HellscapeDownsideReducedElementalResistances', 1, 1, -8.00, 'scourge_detriment', 45, 750, now64(3)),
    ('HellscapeDownsideReducedElementalResistances3_', '-({N}-{N})% to all Elemental Resistances', 'HellscapeDownsideReducedElementalResistances', 1, 1, -10.00, 'scourge_detriment', 68, 1000, now64(3)),
    ('HellscapeDownsideReducedFireResistance0', '-({N}-{N})% to Fire Resistance', 'HellscapeDownsideReducedFireResistance', 0, 2, -11.00, 'scourge_detriment', 1, 500, now64(3)),
    ('HellscapeDownsideReducedFireResistance1', '-({N}-{N})% to Fire Resistance', 'HellscapeDownsideReducedFireResistance', 1, 2, -16.00, 'scourge_detriment', 1, 500, now64(3)),
    ('HellscapeDownsideReducedFireResistance3_', '-({N}-{N})% to Fire Resistance', 'HellscapeDownsideReducedFireResistance', 1, 2, -26.00, 'scourge_detriment', 68, 1000, now64(3)),
    ('HellscapeDownsideReducedFireResistance2', '-({N}-{N})% to Fire Resistance', 'HellscapeDownsideReducedFireResistance', 2, 2, -21.00, 'scourge_detriment', 45, 750, now64(3)),
    ('HellscapeDownsideReducedGlobalDefences0', '({N}-{N})% reduced Global Defences', 'HellscapeDownsideReducedGlobalDefences', 0, 2, -6.00, 'scourge_detriment', 1, 1000, now64(3)),
    ('HellscapeDownsideReducedGlobalDefences1', '({N}-{N})% reduced Global Defences', 'HellscapeDownsideReducedGlobalDefences', 1, 2, -11.00, 'scourge_detriment', 1, 1000, now64(3)),
    ('HellscapeDownsideReducedGlobalDefences3__', '({N}-{N})% reduced Global Defences', 'HellscapeDownsideReducedGlobalDefences', 1, 2, -21.00, 'scourge_detriment', 68, 1000, now64(3)),
    ('HellscapeDownsideReducedGlobalDefences2', '({N}-{N})% reduced Global Defences', 'HellscapeDownsideReducedGlobalDefences', 2, 2, -16.00, 'scourge_detriment', 45, 1000, now64(3)),
    ('HellscapeDownsideReducedLightningResistance0_', '-({N}-{N})% to Lightning Resistance', 'HellscapeDownsideReducedLightningResistance', 1, 3, -11.00, 'scourge_detriment', 1, 500, now64(3)),
    ('HellscapeDownsideReducedLightningResistance1', '-({N}-{N})% to Lightning Resistance', 'HellscapeDownsideReducedLightningResistance', 1, 3, -16.00, 'scourge_detriment', 1, 500, now64(3)),
    ('HellscapeDownsideReducedLightningResistance2', '-({N}-{N})% to Lightning Resistance', 'HellscapeDownsideReducedLightningResistance', 2, 3, -21.00, 'scourge_detriment', 45, 750, now64(3)),
    ('HellscapeDownsideReducedLightningResistance3', '-({N}-{N})% to Lightning Resistance', 'HellscapeDownsideReducedLightningResistance', 3, 3, -26.00, 'scourge_detriment', 68, 1000, now64(3)),
    ('HellscapeUpsideAdditionalDexterity1__', '+({N}-{N}) to Dexterity', 'HellscapeUpsideAdditionalDexterity', 1, 3, 23.00, 'scourge_benefit', 1, 500, now64(3)),
    ('HellscapeUpsideAdditionalDexterity4_', '+({N}-{N}) to Dexterity', 'HellscapeUpsideAdditionalDexterity', 1, 3, 35.00, 'scourge_benefit', 68, 500, now64(3)),
    ('HellscapeUpsideAdditionalDexterity2', '+({N}-{N}) to Dexterity', 'HellscapeUpsideAdditionalDexterity', 2, 3, 27.00, 'scourge_benefit', 45, 500, now64(3)),
    ('HellscapeUpsideAdditionalDexterity3', '+({N}-{N}) to Dexterity', 'HellscapeUpsideAdditionalDexterity', 3, 3, 31.00, 'scourge_benefit', 68, 500, now64(3)),
    ('HellscapeUpsideAdditionalIntelligence1', '+({N}-{N}) to Intelligence', 'HellscapeUpsideAdditionalIntelligence', 1, 4, 23.00, 'scourge_benefit', 1, 500, now64(3)),
    ('HellscapeUpsideAdditionalIntelligence2__', '+({N}-{N}) to Intelligence', 'HellscapeUpsideAdditionalIntelligence', 1, 4, 27.00, 'scourge_benefit', 45, 500, now64(3)),
    ('HellscapeUpsideAdditionalIntelligence3_', '+({N}-{N}) to Intelligence', 'HellscapeUpsideAdditionalIntelligence', 1, 4, 31.00, 'scourge_benefit', 68, 500, now64(3)),
    ('HellscapeUpsideAdditionalIntelligence4', '+({N}-{N}) to Intelligence', 'HellscapeUpsideAdditionalIntelligence', 4, 4, 35.00, 'scourge_benefit', 68, 500, now64(3)),
    ('HellscapeUpsideAdditionalStrength1', '+({N}-{N}) to Strength', 'HellscapeUpsideAdditionalStrength', 1, 4, 23.00, 'scourge_benefit', 1, 500, now64(3)),
    ('HellscapeUpsideAdditionalStrength2', '+({N}-{N}) to Strength', 'HellscapeUpsideAdditionalStrength', 2, 4, 27.00, 'scourge_benefit', 45, 500, now64(3)),
    ('HellscapeUpsideAdditionalStrength3', '+({N}-{N}) to Strength', 'HellscapeUpsideAdditionalStrength', 3, 4, 31.00, 'scourge_benefit', 68, 500, now64(3)),
    ('HellscapeUpsideAdditionalStrength4', '+({N}-{N}) to Strength', 'HellscapeUpsideAdditionalStrength', 4, 4, 35.00, 'scourge_benefit', 68, 500, now64(3)),
    ('HellscapeUpsideAttackLifeLeech2', '({N}-{N})% of Physical Attack Damage Leeched as Life', 'HellscapeUpsideAttackLifeLeech', 2, 4, 30.00, 'scourge_benefit', 45, 1000, now64(3)),
    ('HellscapeUpsideAttackLifeLeech3', '({N}-{N})% of Physical Attack Damage Leeched as Life', 'HellscapeUpsideAttackLifeLeech', 3, 4, 40.00, 'scourge_benefit', 68, 1000, now64(3)),
    ('HellscapeUpsideAttackLifeLeech4', '({N}-{N})% of Physical Attack Damage Leeched as Life', 'HellscapeUpsideAttackLifeLeech', 4, 4, 50.00, 'scourge_benefit', 68, 1000, now64(3)),
    ('HellscapeUpsideAttackManaLifeLeech2', '({N}-{N})% of Physical Attack Damage Leeched as Mana', 'HellscapeUpsideAttackManaLifeLeech', 2, 4, 30.00, 'scourge_benefit', 45, 1000, now64(3)),
    ('HellscapeUpsideAttackManaLifeLeech3', '({N}-{N})% of Physical Attack Damage Leeched as Mana', 'HellscapeUpsideAttackManaLifeLeech', 3, 4, 40.00, 'scourge_benefit', 68, 1000, now64(3)),
    ('HellscapeUpsideAttackManaLifeLeech4', '({N}-{N})% of Physical Attack Damage Leeched as Mana', 'HellscapeUpsideAttackManaLifeLeech', 4, 4, 50.00, 'scourge_benefit', 68, 1000, now64(3)),
    ('HellscapeUpsideChanceToAvoidBleeding2_', '({N}-{N})% chance to Avoid Bleeding', 'HellscapeUpsideChanceToAvoidBleeding', 1, 4, 30.00, 'scourge_benefit', 45, 500, now64(3)),
    ('HellscapeUpsideChanceToAvoidBleeding3_', '({N}-{N})% chance to Avoid Bleeding', 'HellscapeUpsideChanceToAvoidBleeding', 1, 4, 35.00, 'scourge_benefit', 68, 500, now64(3)),
    ('HellscapeUpsideChanceToAvoidBleeding4', '({N}-{N})% chance to Avoid Bleeding', 'HellscapeUpsideChanceToAvoidBleeding', 4, 4, 40.00, 'scourge_benefit', 68, 500, now64(3)),
    ('HellscapeUpsideChanceToAvoidFreezeAndChill2_', '({N}-{N})% chance to Avoid being Chilled
({N}-{N})% chance to Avoid being Frozen', 'HellscapeUpsideChanceToAvoidFreezeAndChill', 1, 4, 30.00, 'scourge_benefit', 45, 500, now64(3)),
    ('HellscapeUpsideChanceToAvoidFreezeAndChill3', '({N}-{N})% chance to Avoid being Chilled
({N}-{N})% chance to Avoid being Frozen', 'HellscapeUpsideChanceToAvoidFreezeAndChill', 3, 4, 35.00, 'scourge_benefit', 68, 500, now64(3)),
    ('HellscapeUpsideChanceToAvoidFreezeAndChill4', '({N}-{N})% chance to Avoid being Chilled
({N}-{N})% chance to Avoid being Frozen', 'HellscapeUpsideChanceToAvoidFreezeAndChill', 4, 4, 40.00, 'scourge_benefit', 68, 500, now64(3)),
    ('HellscapeUpsideChanceToAvoidIgniteAndBurning2', '({N}-{N})% chance to Avoid being Ignited', 'HellscapeUpsideChanceToAvoidIgniteAndBurning', 2, 4, 30.00, 'scourge_benefit', 45, 500, now64(3)),
    ('HellscapeUpsideChanceToAvoidIgniteAndBurning3', '({N}-{N})% chance to Avoid being Ignited', 'HellscapeUpsideChanceToAvoidIgniteAndBurning', 3, 4, 35.00, 'scourge_benefit', 68, 500, now64(3)),
    ('HellscapeUpsideChanceToAvoidIgniteAndBurning4', '({N}-{N})% chance to Avoid being Ignited', 'HellscapeUpsideChanceToAvoidIgniteAndBurning', 4, 4, 40.00, 'scourge_benefit', 68, 500, now64(3)),
    ('HellscapeUpsideChanceToAvoidPoison2', '({N}-{N})% chance to Avoid being Poisoned', 'HellscapeUpsideChanceToAvoidPoison', 2, 4, 30.00, 'scourge_benefit', 45, 500, now64(3)),
    ('HellscapeUpsideChanceToAvoidPoison3', '({N}-{N})% chance to Avoid being Poisoned', 'HellscapeUpsideChanceToAvoidPoison', 3, 4, 35.00, 'scourge_benefit', 68, 500, now64(3)),
    ('HellscapeUpsideChanceToAvoidPoison4', '({N}-{N})% chance to Avoid being Poisoned', 'HellscapeUpsideChanceToAvoidPoison', 4, 4, 40.00, 'scourge_benefit', 68, 500, now64(3)),
    ('HellscapeUpsideChanceToAvoidShock4_', '({N}-{N})% chance to Avoid being Shocked', 'HellscapeUpsideChanceToAvoidShock', 1, 3, 40.00, 'scourge_benefit', 68, 500, now64(3)),
    ('HellscapeUpsideChanceToAvoidShock2', '({N}-{N})% chance to Avoid being Shocked', 'HellscapeUpsideChanceToAvoidShock', 2, 3, 30.00, 'scourge_benefit', 45, 500, now64(3)),
    ('HellscapeUpsideChanceToAvoidShock3', '({N}-{N})% chance to Avoid being Shocked', 'HellscapeUpsideChanceToAvoidShock', 3, 3, 35.00, 'scourge_benefit', 68, 500, now64(3)),
    ('HellscapeUpsideChanceToGainEnduranceChargeOnKill1__', '({N}-{N})% chance to gain an Endurance Charge on Kill', 'HellscapeUpsideChanceToGainEnduranceChargeOnKill', 1, 3, 6.00, 'scourge_benefit', 1, 200, now64(3)),
    ('HellscapeUpsideChanceToGainEnduranceChargeOnKill4_', '({N}-{N})% chance to gain an Endurance Charge on Kill', 'HellscapeUpsideChanceToGainEnduranceChargeOnKill', 1, 3, 12.00, 'scourge_benefit', 68, 200, now64(3)),
    ('HellscapeUpsideChanceToGainEnduranceChargeOnKill2', '({N}-{N})% chance to gain an Endurance Charge on Kill', 'HellscapeUpsideChanceToGainEnduranceChargeOnKill', 2, 3, 8.00, 'scourge_benefit', 45, 200, now64(3)),
    ('HellscapeUpsideChanceToGainEnduranceChargeOnKill3', '({N}-{N})% chance to gain an Endurance Charge on Kill', 'HellscapeUpsideChanceToGainEnduranceChargeOnKill', 3, 3, 10.00, 'scourge_benefit', 68, 200, now64(3)),
    ('HellscapeUpsideChanceToGainFrenzyChargeOnKill1', '({N}-{N})% chance to gain a Frenzy Charge on Kill', 'HellscapeUpsideChanceToGainFrenzyChargeOnKill', 1, 4, 6.00, 'scourge_benefit', 1, 200, now64(3)),
    ('HellscapeUpsideChanceToGainFrenzyChargeOnKill2_', '({N}-{N})% chance to gain a Frenzy Charge on Kill', 'HellscapeUpsideChanceToGainFrenzyChargeOnKill', 1, 4, 8.00, 'scourge_benefit', 45, 200, now64(3)),
    ('HellscapeUpsideChanceToGainFrenzyChargeOnKill3', '({N}-{N})% chance to gain a Frenzy Charge on Kill', 'HellscapeUpsideChanceToGainFrenzyChargeOnKill', 3, 4, 10.00, 'scourge_benefit', 68, 200, now64(3)),
    ('HellscapeUpsideChanceToGainFrenzyChargeOnKill4', '({N}-{N})% chance to gain a Frenzy Charge on Kill', 'HellscapeUpsideChanceToGainFrenzyChargeOnKill', 4, 4, 12.00, 'scourge_benefit', 68, 200, now64(3)),
    ('HellscapeUpsideChanceToGainPowerChargeOnKill1', '({N}-{N})% chance to gain a Power Charge on Kill', 'HellscapeUpsideChanceToGainPowerChargeOnKill', 1, 3, 6.00, 'scourge_benefit', 1, 200, now64(3)),
    ('HellscapeUpsideChanceToGainPowerChargeOnKill4___', '({N}-{N})% chance to gain a Power Charge on Kill', 'HellscapeUpsideChanceToGainPowerChargeOnKill', 1, 3, 12.00, 'scourge_benefit', 68, 200, now64(3)),
    ('HellscapeUpsideChanceToGainPowerChargeOnKill2', '({N}-{N})% chance to gain a Power Charge on Kill', 'HellscapeUpsideChanceToGainPowerChargeOnKill', 2, 3, 8.00, 'scourge_benefit', 45, 200, now64(3)),
    ('HellscapeUpsideChanceToGainPowerChargeOnKill3', '({N}-{N})% chance to gain a Power Charge on Kill', 'HellscapeUpsideChanceToGainPowerChargeOnKill', 3, 3, 10.00, 'scourge_benefit', 68, 200, now64(3)),
    ('HellscapeUpsideChaosResistance1_', '+({N}-{N})% to Chaos Resistance', 'HellscapeUpsideChaosResistance', 1, 1, 13.00, 'scourge_benefit', 16, 250, now64(3)),
    ('HellscapeUpsideChaosResistance2_', '+({N}-{N})% to Chaos Resistance', 'HellscapeUpsideChaosResistance', 1, 1, 17.00, 'scourge_benefit', 45, 250, now64(3)),
    ('HellscapeUpsideChaosResistance3_', '+({N}-{N})% to Chaos Resistance', 'HellscapeUpsideChaosResistance', 1, 1, 21.00, 'scourge_benefit', 68, 250, now64(3)),
    ('HellscapeUpsideChaosResistance4_', '+({N}-{N})% to Chaos Resistance', 'HellscapeUpsideChaosResistance', 1, 1, 25.00, 'scourge_benefit', 68, 250, now64(3)),
    ('HellscapeUpsideChillEffectivenessOnSelf3_', '({N}-{N})% reduced Effect of Chill on you', 'HellscapeUpsideChillEffectivenessOnSelf', 1, 1, -31.00, 'scourge_benefit', 68, 500, now64(3)),
    ('HellscapeUpsideChillEffectivenessOnSelf4_', '({N}-{N})% reduced Effect of Chill on you', 'HellscapeUpsideChillEffectivenessOnSelf', 1, 1, -36.00, 'scourge_benefit', 68, 500, now64(3)),
    ('HellscapeUpsideColdResistance1', '+({N}-{N})% to Cold Resistance', 'HellscapeUpsideColdResistance', 1, 4, 20.00, 'scourge_benefit', 1, 1000, now64(3)),
    ('HellscapeUpsideColdResistance3_', '+({N}-{N})% to Cold Resistance', 'HellscapeUpsideColdResistance', 1, 4, 30.00, 'scourge_benefit', 68, 1000, now64(3)),
    ('HellscapeUpsideColdResistance2', '+({N}-{N})% to Cold Resistance', 'HellscapeUpsideColdResistance', 2, 4, 25.00, 'scourge_benefit', 45, 1000, now64(3)),
    ('HellscapeUpsideColdResistance4', '+({N}-{N})% to Cold Resistance', 'HellscapeUpsideColdResistance', 4, 4, 35.00, 'scourge_benefit', 68, 1000, now64(3)),
    ('HellscapeUpsideElementalResistance1__', '+{N}% to all Elemental Resistances', 'HellscapeUpsideElementalResistance', 1, 3, 6.00, 'scourge_benefit', 1, 1000, now64(3)),
    ('HellscapeUpsideElementalResistance4_', '+{N}% to all Elemental Resistances', 'HellscapeUpsideElementalResistance', 1, 3, 12.00, 'scourge_benefit', 68, 1000, now64(3)),
    ('HellscapeUpsideElementalResistance2', '+{N}% to all Elemental Resistances', 'HellscapeUpsideElementalResistance', 2, 3, 8.00, 'scourge_benefit', 45, 1000, now64(3)),
    ('HellscapeUpsideElementalResistance3', '+{N}% to all Elemental Resistances', 'HellscapeUpsideElementalResistance', 3, 3, 10.00, 'scourge_benefit', 68, 1000, now64(3)),
    ('HellscapeUpsideFireResistance1', '+({N}-{N})% to Fire Resistance', 'HellscapeUpsideFireResistance', 1, 2, 20.00, 'scourge_benefit', 1, 1000, now64(3)),
    ('HellscapeUpsideFireResistance3_', '+({N}-{N})% to Fire Resistance', 'HellscapeUpsideFireResistance', 1, 2, 30.00, 'scourge_benefit', 68, 1000, now64(3)),
    ('HellscapeUpsideFireResistance4__', '+({N}-{N})% to Fire Resistance', 'HellscapeUpsideFireResistance', 1, 2, 35.00, 'scourge_benefit', 68, 1000, now64(3)),
    ('HellscapeUpsideFireResistance2', '+({N}-{N})% to Fire Resistance', 'HellscapeUpsideFireResistance', 2, 2, 25.00, 'scourge_benefit', 45, 1000, now64(3)),
    ('HellscapeUpsideIncreasedWeaponElementalDamagePercent1', '({N}-{N})% increased Elemental Damage with Attack Skills', 'HellscapeUpsideIncreasedWeaponElementalDamagePercent', 1, 4, 12.00, 'scourge_benefit', 1, 500, now64(3)),
    ('HellscapeUpsideIncreasedWeaponElementalDamagePercent2_', '({N}-{N})% increased Elemental Damage with Attack Skills', 'HellscapeUpsideIncreasedWeaponElementalDamagePercent', 1, 4, 16.00, 'scourge_benefit', 45, 500, now64(3)),
    ('HellscapeUpsideIncreasedWeaponElementalDamagePercent3', '({N}-{N})% increased Elemental Damage with Attack Skills', 'HellscapeUpsideIncreasedWeaponElementalDamagePercent', 3, 4, 20.00, 'scourge_benefit', 68, 500, now64(3)),
    ('HellscapeUpsideIncreasedWeaponElementalDamagePercent4', '({N}-{N})% increased Elemental Damage with Attack Skills', 'HellscapeUpsideIncreasedWeaponElementalDamagePercent', 4, 4, 24.00, 'scourge_benefit', 68, 500, now64(3)),
    ('HellscapeUpsideLightningResistance1', '+({N}-{N})% to Lightning Resistance', 'HellscapeUpsideLightningResistance', 1, 4, 20.00, 'scourge_benefit', 1, 1000, now64(3)),
    ('HellscapeUpsideLightningResistance2__', '+({N}-{N})% to Lightning Resistance', 'HellscapeUpsideLightningResistance', 1, 4, 25.00, 'scourge_benefit', 45, 1000, now64(3)),
    ('HellscapeUpsideLightningResistance3', '+({N}-{N})% to Lightning Resistance', 'HellscapeUpsideLightningResistance', 3, 4, 30.00, 'scourge_benefit', 68, 1000, now64(3)),
    ('HellscapeUpsideLightningResistance4', '+({N}-{N})% to Lightning Resistance', 'HellscapeUpsideLightningResistance', 4, 4, 35.00, 'scourge_benefit', 68, 1000, now64(3)),
    ('HellscapeUpsideManaRegeneration1', '({N}-{N})% increased Mana Regeneration Rate', 'HellscapeUpsideManaRegeneration', 1, 4, 20.00, 'scourge_benefit', 1, 500, now64(3)),
    ('HellscapeUpsideManaRegeneration2', '({N}-{N})% increased Mana Regeneration Rate', 'HellscapeUpsideManaRegeneration', 2, 4, 25.00, 'scourge_benefit', 45, 500, now64(3)),
    ('HellscapeUpsideManaRegeneration3', '({N}-{N})% increased Mana Regeneration Rate', 'HellscapeUpsideManaRegeneration', 3, 4, 35.00, 'scourge_benefit', 68, 500, now64(3)),
    ('HellscapeUpsideManaRegeneration4', '({N}-{N})% increased Mana Regeneration Rate', 'HellscapeUpsideManaRegeneration', 4, 4, 45.00, 'scourge_benefit', 68, 500, now64(3)),
    ('HellscapeUpsideManaRegeneration2b', '({N}-{N})% increased Mana Regeneration Rate', 'HellscapeUpsideManaRegeneration2b', 1, 1, 30.00, 'scourge_benefit', 55, 250, now64(3)),
    ('HellscapeUpsideManaRegeneration3b', '({N}-{N})% increased Mana Regeneration Rate', 'HellscapeUpsideManaRegeneration3b', 1, 1, 40.00, 'scourge_benefit', 68, 250, now64(3)),
    ('HellscapeUpsideMaximumMana1__', '+({N}-{N}) to maximum Mana', 'HellscapeUpsideMaximumMana', 1, 3, 25.00, 'scourge_benefit', 1, 1000, now64(3)),
    ('HellscapeUpsideMaximumMana4_', '+({N}-{N}) to maximum Mana', 'HellscapeUpsideMaximumMana', 1, 3, 40.00, 'scourge_benefit', 68, 1000, now64(3)),
    ('HellscapeUpsideMaximumMana2', '+({N}-{N}) to maximum Mana', 'HellscapeUpsideMaximumMana', 2, 3, 30.00, 'scourge_benefit', 45, 1000, now64(3)),
    ('HellscapeUpsideMaximumMana3', '+({N}-{N}) to maximum Mana', 'HellscapeUpsideMaximumMana', 3, 3, 35.00, 'scourge_benefit', 68, 1000, now64(3)),
    ('HellscapeUpsideMinimumEnduranceCharges1', '+{N} to Minimum Endurance Charges', 'HellscapeUpsideMinimumEnduranceCharges', 1, 1, 1.00, 'scourge_benefit', 68, 100, now64(3)),
    ('HellscapeUpsideMinimumFrenzyCharges1___', '+{N} to Minimum Frenzy Charges', 'HellscapeUpsideMinimumFrenzyCharges', 1, 1, 1.00, 'scourge_benefit', 68, 100, now64(3)),
    ('HellscapeUpsideMinimumPowerCharges1', '+{N} to Minimum Power Charges', 'HellscapeUpsideMinimumPowerCharges', 1, 1, 1.00, 'scourge_benefit', 68, 100, now64(3)),
    ('HellscapeUpsideRarityOfItemsFound1_', '({N}-{N})% increased Rarity of Items found', 'HellscapeUpsideRarityOfItemsFound', 1, 4, 9.00, 'scourge_benefit', 1, 500, now64(3)),
    ('HellscapeUpsideRarityOfItemsFound2_', '({N}-{N})% increased Rarity of Items found', 'HellscapeUpsideRarityOfItemsFound', 1, 4, 11.00, 'scourge_benefit', 45, 500, now64(3)),
    ('HellscapeUpsideRarityOfItemsFound3', '({N}-{N})% increased Rarity of Items found', 'HellscapeUpsideRarityOfItemsFound', 3, 4, 13.00, 'scourge_benefit', 68, 500, now64(3)),
    ('HellscapeUpsideRarityOfItemsFound4', '({N}-{N})% increased Rarity of Items found', 'HellscapeUpsideRarityOfItemsFound', 4, 4, 15.00, 'scourge_benefit', 68, 500, now64(3)),
    ('HellscapeUpsideReducedBurnDuration3__', '({N}-{N})% reduced Ignite Duration on you', 'HellscapeUpsideReducedBurnDuration', 1, 4, 35.00, 'scourge_benefit', 68, 500, now64(3)),
    ('HellscapeUpsideReducedBurnDuration4', '({N}-{N})% reduced Ignite Duration on you', 'HellscapeUpsideReducedBurnDuration', 4, 4, 40.00, 'scourge_benefit', 68, 500, now64(3)),
    ('HellscapeUpsideReducedCurseEffect3', '({N}-{N})% reduced Effect of Curses on you', 'HellscapeUpsideReducedCurseEffect', 3, 4, -16.00, 'scourge_benefit', 68, 500, now64(3)),
    ('HellscapeUpsideReducedCurseEffect4', '({N}-{N})% reduced Effect of Curses on you', 'HellscapeUpsideReducedCurseEffect', 4, 4, -21.00, 'scourge_benefit', 68, 500, now64(3)),
    ('HellscapeUpsideReducedShockEffectOnSelf3', '({N}-{N})% reduced Effect of Shock on you', 'HellscapeUpsideReducedShockEffectOnSelf', 3, 4, -31.00, 'scourge_benefit', 68, 500, now64(3)),
    ('HellscapeUpsideReducedShockEffectOnSelf4', '({N}-{N})% reduced Effect of Shock on you', 'HellscapeUpsideReducedShockEffectOnSelf', 4, 4, -36.00, 'scourge_benefit', 68, 500, now64(3)),
    ('IncreasedAccuracyNew1_', '+({N}-{N}) to Accuracy Rating', 'IncreasedAccuracyNew', 1, 4, 100.00, 'suffix', 1, 600, now64(3)),
    ('IncreasedAccuracyNew5_', '+({N}-{N}) to Accuracy Rating', 'IncreasedAccuracyNew', 1, 4, 480.00, 'suffix', 75, 1000, now64(3)),
    ('IncreasedAccuracyNew2', '+({N}-{N}) to Accuracy Rating', 'IncreasedAccuracyNew', 2, 4, 165.00, 'suffix', 20, 1000, now64(3)),
    ('IncreasedAccuracyNew3', '+({N}-{N}) to Accuracy Rating', 'IncreasedAccuracyNew', 3, 4, 250.00, 'suffix', 40, 1000, now64(3)),
    ('IncreasedAccuracyNew4', '+({N}-{N}) to Accuracy Rating', 'IncreasedAccuracyNew', 4, 4, 350.00, 'suffix', 60, 1000, now64(3)),
    ('IncreasedAttackSpeed1', '({N}-{N})% increased Attack Speed', 'IncreasedAttackSpeed', 1, 1, 7.00, 'suffix', 1, 500, now64(3)),
    ('IncreasedCastSpeed1', '({N}-{N})% increased Cast Speed', 'IncreasedCastSpeed', 1, 3, 8.00, 'suffix', 2, 800, now64(3)),
    ('IncreasedCastSpeed2', '({N}-{N})% increased Cast Speed', 'IncreasedCastSpeed', 2, 3, 12.00, 'suffix', 15, 800, now64(3)),
    ('IncreasedCastSpeed3', '({N}-{N})% increased Cast Speed', 'IncreasedCastSpeed', 3, 3, 16.00, 'suffix', 30, 800, now64(3)),
    ('IncreasedEnergyShield1', '+({N}-{N}) to maximum Energy Shield', 'IncreasedEnergyShield', 1, 11, 3.00, 'prefix', 3, 1000, now64(3)),
    ('IncreasedEnergyShield2', '+({N}-{N}) to maximum Energy Shield', 'IncreasedEnergyShield', 2, 11, 8.00, 'prefix', 11, 1000, now64(3)),
    ('IncreasedEnergyShield3', '+({N}-{N}) to maximum Energy Shield', 'IncreasedEnergyShield', 3, 11, 12.00, 'prefix', 17, 1000, now64(3)),
    ('IncreasedEnergyShield4', '+({N}-{N}) to maximum Energy Shield', 'IncreasedEnergyShield', 4, 11, 15.00, 'prefix', 23, 1000, now64(3)),
    ('IncreasedEnergyShield5', '+({N}-{N}) to maximum Energy Shield', 'IncreasedEnergyShield', 5, 11, 19.00, 'prefix', 29, 1000, now64(3)),
    ('IncreasedEnergyShield6', '+({N}-{N}) to maximum Energy Shield', 'IncreasedEnergyShield', 6, 11, 22.00, 'prefix', 35, 1000, now64(3)),
    ('IncreasedEnergyShield7', '+({N}-{N}) to maximum Energy Shield', 'IncreasedEnergyShield', 7, 11, 26.00, 'prefix', 42, 1000, now64(3)),
    ('IncreasedEnergyShield8', '+({N}-{N}) to maximum Energy Shield', 'IncreasedEnergyShield', 8, 11, 31.00, 'prefix', 50, 1000, now64(3)),
    ('IncreasedEnergyShield9', '+({N}-{N}) to maximum Energy Shield', 'IncreasedEnergyShield', 9, 11, 37.00, 'prefix', 59, 1000, now64(3)),
    ('IncreasedEnergyShield10', '+({N}-{N}) to maximum Energy Shield', 'IncreasedEnergyShield', 10, 11, 43.00, 'prefix', 68, 1000, now64(3)),
    ('IncreasedEnergyShield11', '+({N}-{N}) to maximum Energy Shield', 'IncreasedEnergyShield', 11, 11, 47.00, 'prefix', 74, 1000, now64(3)),
    ('IncreasedEvasionRating1', '+({N}-{N}) to Evasion Rating', 'IncreasedEvasionRating', 1, 7, 10.00, 'prefix', 1, 1000, now64(3)),
    ('IncreasedEvasionRating2', '+({N}-{N}) to Evasion Rating', 'IncreasedEvasionRating', 2, 7, 35.00, 'prefix', 18, 1000, now64(3)),
    ('IncreasedEvasionRating3', '+({N}-{N}) to Evasion Rating', 'IncreasedEvasionRating', 3, 7, 60.00, 'prefix', 29, 1000, now64(3)),
    ('IncreasedEvasionRating4', '+({N}-{N}) to Evasion Rating', 'IncreasedEvasionRating', 4, 7, 80.00, 'prefix', 42, 1000, now64(3)),
    ('IncreasedEvasionRating5', '+({N}-{N}) to Evasion Rating', 'IncreasedEvasionRating', 5, 7, 120.00, 'prefix', 58, 1000, now64(3)),
    ('IncreasedEvasionRating6', '+({N}-{N}) to Evasion Rating', 'IncreasedEvasionRating', 6, 7, 150.00, 'prefix', 72, 1000, now64(3)),
    ('IncreasedEvasionRating7', '+({N}-{N}) to Evasion Rating', 'IncreasedEvasionRating', 7, 7, 170.00, 'prefix', 84, 1000, now64(3)),
    ('IncreasedMana1', '+({N}-{N}) to maximum Mana', 'IncreasedMana', 1, 13, 19.00, 'prefix', 1, 1000, now64(3)),
    ('IncreasedMana2', '+({N}-{N}) to maximum Mana', 'IncreasedMana', 2, 13, 24.00, 'prefix', 11, 1000, now64(3)),
    ('IncreasedMana3', '+({N}-{N}) to maximum Mana', 'IncreasedMana', 3, 13, 29.00, 'prefix', 17, 1000, now64(3)),
    ('IncreasedMana4', '+({N}-{N}) to maximum Mana', 'IncreasedMana', 4, 13, 34.00, 'prefix', 23, 1000, now64(3)),
    ('IncreasedMana5', '+({N}-{N}) to maximum Mana', 'IncreasedMana', 5, 13, 39.00, 'prefix', 29, 1000, now64(3)),
    ('IncreasedMana6', '+({N}-{N}) to maximum Mana', 'IncreasedMana', 6, 13, 44.00, 'prefix', 35, 1000, now64(3)),
    ('IncreasedMana7', '+({N}-{N}) to maximum Mana', 'IncreasedMana', 7, 13, 49.00, 'prefix', 42, 1000, now64(3)),
    ('IncreasedMana8', '+({N}-{N}) to maximum Mana', 'IncreasedMana', 8, 13, 54.00, 'prefix', 51, 1000, now64(3)),
    ('IncreasedMana9', '+({N}-{N}) to maximum Mana', 'IncreasedMana', 9, 13, 59.00, 'prefix', 60, 1000, now64(3)),
    ('IncreasedMana10', '+({N}-{N}) to maximum Mana', 'IncreasedMana', 10, 13, 64.00, 'prefix', 69, 1000, now64(3)),
    ('IncreasedMana11', '+({N}-{N}) to maximum Mana', 'IncreasedMana', 11, 13, 68.00, 'prefix', 75, 1000, now64(3)),
    ('IncreasedMana12', '+({N}-{N}) to maximum Mana', 'IncreasedMana', 12, 13, 73.00, 'prefix', 81, 1000, now64(3)),
    ('IncreasedMana13', '+({N}-{N}) to maximum Mana', 'IncreasedMana', 13, 13, 78.00, 'prefix', 85, 1000, now64(3)),
    ('Intelligence1', '+({N}-{N}) to Intelligence', 'Intelligence', 1, 9, 12.00, 'suffix', 1, 1000, now64(3)),
    ('Intelligence2', '+({N}-{N}) to Intelligence', 'Intelligence', 2, 9, 17.00, 'suffix', 11, 1000, now64(3)),
    ('Intelligence3', '+({N}-{N}) to Intelligence', 'Intelligence', 3, 9, 22.00, 'suffix', 22, 1000, now64(3)),
    ('Intelligence4', '+({N}-{N}) to Intelligence', 'Intelligence', 4, 9, 27.00, 'suffix', 33, 1000, now64(3)),
    ('Intelligence5', '+({N}-{N}) to Intelligence', 'Intelligence', 5, 9, 32.00, 'suffix', 44, 1000, now64(3)),
    ('Intelligence6', '+({N}-{N}) to Intelligence', 'Intelligence', 6, 9, 37.00, 'suffix', 55, 1000, now64(3)),
    ('Intelligence7', '+({N}-{N}) to Intelligence', 'Intelligence', 7, 9, 42.00, 'suffix', 66, 1000, now64(3)),
    ('Intelligence8', '+({N}-{N}) to Intelligence', 'Intelligence', 8, 9, 50.00, 'suffix', 74, 1000, now64(3)),
    ('Intelligence9', '+({N}-{N}) to Intelligence', 'Intelligence', 9, 9, 55.00, 'suffix', 82, 1000, now64(3)),
    ('ItemFoundRarityIncrease1', '({N}-{N})% increased Rarity of Items found', 'ItemFoundRarityIncrease', 1, 4, 10.00, 'suffix', 3, 1000, now64(3)),
    ('ItemFoundRarityIncrease2', '({N}-{N})% increased Rarity of Items found', 'ItemFoundRarityIncrease', 2, 4, 14.00, 'suffix', 30, 1000, now64(3)),
    ('ItemFoundRarityIncrease3', '({N}-{N})% increased Rarity of Items found', 'ItemFoundRarityIncrease', 3, 4, 20.00, 'suffix', 53, 1000, now64(3)),
    ('ItemFoundRarityIncrease4', '({N}-{N})% increased Rarity of Items found', 'ItemFoundRarityIncrease', 4, 4, 26.00, 'suffix', 75, 1000, now64(3)),
    ('ItemFoundRarityIncreasePrefix1', '({N}-{N})% increased Rarity of Items found', 'ItemFoundRarityIncreasePrefix', 1, 3, 12.00, 'prefix', 20, 1000, now64(3)),
    ('ItemFoundRarityIncreasePrefix4_', '({N}-{N})% increased Rarity of Items found', 'ItemFoundRarityIncreasePrefix', 1, 3, 28.00, 'prefix', 84, 1000, now64(3)),
    ('ItemFoundRarityIncreasePrefix2', '({N}-{N})% increased Rarity of Items found', 'ItemFoundRarityIncreasePrefix', 2, 3, 18.00, 'prefix', 39, 1000, now64(3)),
    ('ItemFoundRarityIncreasePrefix3', '({N}-{N})% increased Rarity of Items found', 'ItemFoundRarityIncreasePrefix', 3, 3, 24.00, 'prefix', 62, 1000, now64(3)),
    ('LifeGainedFromEnemyDeath1', 'Gain ({N}-{N}) Life per Enemy Killed', 'LifeGainedFromEnemyDeath', 1, 6, 10.00, 'suffix', 1, 500, now64(3)),
    ('LifeGainedFromEnemyDeath2', 'Gain ({N}-{N}) Life per Enemy Killed', 'LifeGainedFromEnemyDeath', 2, 6, 18.00, 'suffix', 23, 500, now64(3)),
    ('LifeGainedFromEnemyDeath3', 'Gain ({N}-{N}) Life per Enemy Killed', 'LifeGainedFromEnemyDeath', 3, 6, 32.00, 'suffix', 40, 500, now64(3)),
    ('LifeGainedFromEnemyDeath4', 'Gain ({N}-{N}) Life per Enemy Killed', 'LifeGainedFromEnemyDeath', 4, 6, 44.00, 'suffix', 52, 500, now64(3)),
    ('LifeGainedFromEnemyDeath5', 'Gain ({N}-{N}) Life per Enemy Killed', 'LifeGainedFromEnemyDeath', 5, 6, 72.00, 'suffix', 66, 500, now64(3)),
    ('LifeGainedFromEnemyDeath6', 'Gain ({N}-{N}) Life per Enemy Killed', 'LifeGainedFromEnemyDeath', 6, 6, 110.00, 'suffix', 81, 500, now64(3)),
    ('LifeGainPerTarget1', 'Gain {N} Life per Enemy Hit with Attacks', 'LifeGainPerTarget', 1, 1, 2.00, 'suffix', 8, 1000, now64(3)),
    ('LifeLeechPermyriadSuffix1', '({N}-{N})% of Physical Attack Damage Leeched as Life', 'LifeLeechPermyriadSuffix', 1, 1, 40.00, 'suffix', 50, 1000, now64(3)),
    ('LightningDamagePercent1', '({N}-{N})% increased Lightning Damage', 'LightningDamagePercent', 1, 4, 12.00, 'suffix', 10, 500, now64(3)),
    ('LightningDamagePercent2', '({N}-{N})% increased Lightning Damage', 'LightningDamagePercent', 2, 4, 15.00, 'suffix', 23, 500, now64(3)),
    ('LightningDamagePercent3', '({N}-{N})% increased Lightning Damage', 'LightningDamagePercent', 3, 4, 18.00, 'suffix', 36, 500, now64(3)),
    ('LightningDamagePercent4', '({N}-{N})% increased Lightning Damage', 'LightningDamagePercent', 4, 4, 22.00, 'suffix', 50, 500, now64(3)),
    ('LightningResist1', '+({N}-{N})% to Lightning Resistance', 'LightningResist', 1, 8, 11.00, 'suffix', 1, 1000, now64(3)),
    ('LightningResist2', '+({N}-{N})% to Lightning Resistance', 'LightningResist', 2, 8, 17.00, 'suffix', 13, 1000, now64(3)),
    ('LightningResist3', '+({N}-{N})% to Lightning Resistance', 'LightningResist', 3, 8, 23.00, 'suffix', 25, 1000, now64(3)),
    ('LightningResist4', '+({N}-{N})% to Lightning Resistance', 'LightningResist', 4, 8, 29.00, 'suffix', 37, 1000, now64(3)),
    ('LightningResist5', '+({N}-{N})% to Lightning Resistance', 'LightningResist', 5, 8, 35.00, 'suffix', 49, 1000, now64(3)),
    ('LightningResist6', '+({N}-{N})% to Lightning Resistance', 'LightningResist', 6, 8, 41.00, 'suffix', 60, 1000, now64(3)),
    ('LightningResist7', '+({N}-{N})% to Lightning Resistance', 'LightningResist', 7, 8, 45.00, 'suffix', 72, 1000, now64(3)),
    ('LightningResist8', '+({N}-{N})% to Lightning Resistance', 'LightningResist', 8, 8, 48.00, 'suffix', 84, 1000, now64(3)),
    ('LightRadiusAndAccuracy3', '{N}% increased Light Radius
({N}-{N})% increased Global Accuracy Rating', 'LightRadiusAndAccuracy', 3, 3, 20.00, 'suffix', 30, 1000, now64(3)),
    ('LightRadiusAndAccuracyNew1', '{N}% increased Light Radius
({N}-{N})% increased Global Accuracy Rating', 'LightRadiusAndAccuracyNew', 1, 2, 11.00, 'suffix', 8, 1000, now64(3)),
    ('LightRadiusAndAccuracyNew2', '{N}% increased Light Radius
({N}-{N})% increased Global Accuracy Rating', 'LightRadiusAndAccuracyNew', 2, 2, 15.00, 'suffix', 15, 1000, now64(3)),
    ('ManaGainedFromEnemyDeath1', 'Gain ({N}-{N}) Mana per Enemy Killed', 'ManaGainedFromEnemyDeath', 1, 6, 6.00, 'suffix', 1, 500, now64(3)),
    ('ManaGainedFromEnemyDeath2', 'Gain ({N}-{N}) Mana per Enemy Killed', 'ManaGainedFromEnemyDeath', 2, 6, 10.00, 'suffix', 24, 500, now64(3)),
    ('ManaGainedFromEnemyDeath3', 'Gain ({N}-{N}) Mana per Enemy Killed', 'ManaGainedFromEnemyDeath', 3, 6, 15.00, 'suffix', 40, 500, now64(3)),
    ('ManaGainedFromEnemyDeath4', 'Gain ({N}-{N}) Mana per Enemy Killed', 'ManaGainedFromEnemyDeath', 4, 6, 25.00, 'suffix', 52, 500, now64(3)),
    ('ManaGainedFromEnemyDeath5', 'Gain ({N}-{N}) Mana per Enemy Killed', 'ManaGainedFromEnemyDeath', 5, 6, 37.00, 'suffix', 66, 500, now64(3)),
    ('ManaGainedFromEnemyDeath6', 'Gain ({N}-{N}) Mana per Enemy Killed', 'ManaGainedFromEnemyDeath', 6, 6, 50.00, 'suffix', 81, 500, now64(3)),
    ('ManaLeechPermyriadSuffix1', '({N}-{N})% of Physical Attack Damage Leeched as Mana', 'ManaLeechPermyriadSuffix', 1, 1, 40.00, 'suffix', 50, 1000, now64(3)),
    ('ManaRegeneration1', '({N}-{N})% increased Mana Regeneration Rate', 'ManaRegeneration', 1, 6, 19.00, 'suffix', 2, 1000, now64(3)),
    ('ManaRegeneration2', '({N}-{N})% increased Mana Regeneration Rate', 'ManaRegeneration', 2, 6, 29.00, 'suffix', 18, 1000, now64(3)),
    ('ManaRegeneration3', '({N}-{N})% increased Mana Regeneration Rate', 'ManaRegeneration', 3, 6, 39.00, 'suffix', 29, 1000, now64(3)),
    ('ManaRegeneration4', '({N}-{N})% increased Mana Regeneration Rate', 'ManaRegeneration', 4, 6, 49.00, 'suffix', 42, 1000, now64(3)),
    ('ManaRegeneration5', '({N}-{N})% increased Mana Regeneration Rate', 'ManaRegeneration', 5, 6, 59.00, 'suffix', 55, 1000, now64(3)),
    ('ManaRegeneration6', '({N}-{N})% increased Mana Regeneration Rate', 'ManaRegeneration', 6, 6, 69.00, 'suffix', 79, 1000, now64(3)),
    ('Strength1', '+({N}-{N}) to Strength', 'Strength', 1, 9, 12.00, 'suffix', 1, 1000, now64(3)),
    ('Strength2', '+({N}-{N}) to Strength', 'Strength', 2, 9, 17.00, 'suffix', 11, 1000, now64(3)),
    ('Strength3', '+({N}-{N}) to Strength', 'Strength', 3, 9, 22.00, 'suffix', 22, 1000, now64(3)),
    ('Strength4', '+({N}-{N}) to Strength', 'Strength', 4, 9, 27.00, 'suffix', 33, 1000, now64(3)),
    ('Strength5', '+({N}-{N}) to Strength', 'Strength', 5, 9, 32.00, 'suffix', 44, 1000, now64(3)),
    ('Strength6', '+({N}-{N}) to Strength', 'Strength', 6, 9, 37.00, 'suffix', 55, 1000, now64(3)),
    ('Strength7', '+({N}-{N}) to Strength', 'Strength', 7, 9, 42.00, 'suffix', 66, 1000, now64(3)),
    ('Strength8', '+({N}-{N}) to Strength', 'Strength', 8, 9, 50.00, 'suffix', 74, 1000, now64(3)),
    ('Strength9', '+({N}-{N}) to Strength', 'Strength', 9, 9, 55.00, 'suffix', 82, 1000, now64(3)),
    ('V2AddedColdDamageCorrupted1', 'Adds ({N}-{N}) to ({N}-{N}) Cold Damage to Spells and Attacks', 'V2AddedColdDamageCorrupted', 1, 3, 8.00, 'corrupted', 1, 1000, now64(3)),
    ('V2AddedColdDamageCorrupted2', 'Adds ({N}-{N}) to ({N}-{N}) Cold Damage to Spells and Attacks', 'V2AddedColdDamageCorrupted', 2, 3, 16.00, 'corrupted', 31, 1000, now64(3)),
    ('V2AddedColdDamageCorrupted3', 'Adds ({N}-{N}) to ({N}-{N}) Cold Damage to Spells and Attacks', 'V2AddedColdDamageCorrupted', 3, 3, 28.00, 'corrupted', 81, 250, now64(3)),
    ('V2AddedFireDamageCorrupted1', 'Adds ({N}-{N}) to ({N}-{N}) Fire Damage to Spells and Attacks', 'V2AddedFireDamageCorrupted', 1, 3, 8.00, 'corrupted', 1, 1000, now64(3)),
    ('V2AddedFireDamageCorrupted2', 'Adds ({N}-{N}) to ({N}-{N}) Fire Damage to Spells and Attacks', 'V2AddedFireDamageCorrupted', 2, 3, 18.00, 'corrupted', 31, 1000, now64(3)),
    ('V2AddedFireDamageCorrupted3', 'Adds ({N}-{N}) to ({N}-{N}) Fire Damage to Spells and Attacks', 'V2AddedFireDamageCorrupted', 3, 3, 33.00, 'corrupted', 82, 250, now64(3)),
    ('V2AddedLightningDamageCorrupted1', 'Adds {N} to ({N}-{N}) Lightning Damage to Spells and Attacks', 'V2AddedLightningDamageCorrupted', 1, 3, 15.00, 'corrupted', 1, 1000, now64(3)),
    ('V2AddedLightningDamageCorrupted2', 'Adds ({N}-{N}) to ({N}-{N}) Lightning Damage to Spells and Attacks', 'V2AddedLightningDamageCorrupted', 2, 3, 28.00, 'corrupted', 31, 1000, now64(3)),
    ('V2AddedLightningDamageCorrupted3', 'Adds ({N}-{N}) to ({N}-{N}) Lightning Damage to Spells and Attacks', 'V2AddedLightningDamageCorrupted', 3, 3, 52.00, 'corrupted', 83, 250, now64(3)),
    ('V2AllResistancesCorrupted', '+({N}-{N})% to all Elemental Resistances', 'V2AllResistancesCorrupted', 1, 1, 16.00, 'corrupted', 1, 1000, now64(3)),
    ('V2AngerSkillReducedCorrupted', 'Grants Level {N} Anger Skill', 'V2AngerSkillReducedCorrupted', 1, 1, 21.00, 'corrupted', 56, 500, now64(3)),
    ('V2AvoidIgniteCorrupted', 'Cannot be Ignited', 'V2AvoidIgniteCorrupted', 1, 1, 1.00, 'corrupted', 40, 1000, now64(3)),
    ('V2CannotBePoisonedCorrupted', 'Cannot be Poisoned', 'V2CannotBePoisonedCorrupted', 1, 1, 1.00, 'corrupted', 40, 1000, now64(3)),
    ('V2CannotGainBleedingCorrupted_', 'Bleeding cannot be inflicted on you', 'V2CannotGainBleedingCorrupted', 1, 1, 1.00, 'corrupted', 60, 500, now64(3)),
    ('V2ConductivitySkillCorrupted', 'Grants Level {N} Conductivity Skill', 'V2ConductivitySkillCorrupted', 1, 1, 23.00, 'corrupted', 56, 500, now64(3)),
    ('V2DespairSkillCorrupted', 'Grants Level {N} Despair Skill', 'V2DespairSkillCorrupted', 1, 1, 23.00, 'corrupted', 56, 500, now64(3)),
    ('V2FlammabilitySkillCorrupted', 'Grants Level {N} Flammability Skill', 'V2FlammabilitySkillCorrupted', 1, 1, 23.00, 'corrupted', 56, 500, now64(3)),
    ('V2FrostbiteSkillCorrupted', 'Grants Level {N} Frostbite Skill', 'V2FrostbiteSkillCorrupted', 1, 1, 23.00, 'corrupted', 56, 500, now64(3)),
    ('V2HatredSkillCorrupted', 'Grants Level {N} Hatred Skill', 'V2HatredSkillCorrupted', 1, 1, 21.00, 'corrupted', 56, 500, now64(3)),
    ('V2IncreasedAttackSpeedCorrupted', '({N}-{N})% increased Attack Speed', 'V2IncreasedAttackSpeedCorrupted', 1, 1, 10.00, 'corrupted', 1, 500, now64(3)),
    ('V2IncreasedAuraEffectAngerCorrupted', 'Anger has ({N}-{N})% increased Aura Effect', 'V2IncreasedAuraEffectAngerCorrupted', 1, 1, 20.00, 'corrupted', 45, 1000, now64(3)),
    ('V2IncreasedAuraEffectDeterminationCorrupted', 'Determination has ({N}-{N})% increased Aura Effect', 'V2IncreasedAuraEffectDeterminationCorrupted', 1, 1, 20.00, 'corrupted', 45, 1000, now64(3)),
    ('V2IncreasedAuraEffectDisciplineCorrupted', 'Discipline has ({N}-{N})% increased Aura Effect', 'V2IncreasedAuraEffectDisciplineCorrupted', 1, 1, 20.00, 'corrupted', 45, 1000, now64(3)),
    ('V2IncreasedAuraEffectGraceCorrupted', 'Grace has ({N}-{N})% increased Aura Effect', 'V2IncreasedAuraEffectGraceCorrupted', 1, 1, 20.00, 'corrupted', 45, 1000, now64(3)),
    ('V2IncreasedAuraEffectHatredCorrupted', 'Hatred has ({N}-{N})% increased Aura Effect', 'V2IncreasedAuraEffectHatredCorrupted', 1, 1, 20.00, 'corrupted', 45, 1000, now64(3)),
    ('V2IncreasedAuraEffectMalevolenceCorrupted', 'Malevolence has ({N}-{N})% increased Aura Effect', 'V2IncreasedAuraEffectMalevolenceCorrupted', 1, 1, 20.00, 'corrupted', 45, 1000, now64(3)),
    ('V2IncreasedAuraEffectPrideCorrupted', 'Pride has ({N}-{N})% increased Aura Effect', 'V2IncreasedAuraEffectPrideCorrupted', 1, 1, 20.00, 'corrupted', 45, 1000, now64(3)),
    ('V2IncreasedAuraEffectWrathCorrupted', 'Wrath has ({N}-{N})% increased Aura Effect', 'V2IncreasedAuraEffectWrathCorrupted', 1, 1, 20.00, 'corrupted', 45, 1000, now64(3)),
    ('V2IncreasedAuraEffectZealotryCorrupted_', 'Zealotry has ({N}-{N})% increased Aura Effect', 'V2IncreasedAuraEffectZealotryCorrupted', 1, 1, 20.00, 'corrupted', 45, 1000, now64(3)),
    ('V2IncreasedCastSpeedCorrupted_', '({N}-{N})% increased Cast Speed', 'V2IncreasedCastSpeedCorrupted', 1, 1, 10.00, 'corrupted', 1, 500, now64(3)),
    ('V2IncreasedDexterityStrengthCorrupted', '({N}-{N})% increased Dexterity
({N}-{N})% increased Strength', 'V2IncreasedDexterityStrengthCorrupted', 1, 1, 6.00, 'corrupted', 1, 1000, now64(3)),
    ('V2IncreasedGlobalPhysicalDamageCorrupted', '({N}-{N})% increased Global Physical Damage', 'V2IncreasedGlobalPhysicalDamageCorrupted', 1, 1, 25.00, 'corrupted', 1, 500, now64(3)),
    ('V2IncreasedIntelligenceDexterityCorrupted', '({N}-{N})% increased Intelligence
({N}-{N})% increased Dexterity', 'V2IncreasedIntelligenceDexterityCorrupted', 1, 1, 6.00, 'corrupted', 1, 1000, now64(3)),
    ('V2IncreasedStrengthIntelligenceCorrupted_', '({N}-{N})% increased Strength
({N}-{N})% increased Intelligence', 'V2IncreasedStrengthIntelligenceCorrupted', 1, 1, 6.00, 'corrupted', 1, 1000, now64(3)),
    ('V2ItemRarityCorrupted_', '({N}-{N})% increased Rarity of Items found', 'V2ItemRarityCorrupted', 1, 1, 30.00, 'corrupted', 60, 1000, now64(3)),
    ('V2ManaOnHitCorrupted', 'Gain ({N}-{N}) Mana per Enemy Hit with Attacks', 'V2ManaOnHitCorrupted', 1, 1, 6.00, 'corrupted', 40, 500, now64(3)),
    ('V2PrideSkillCorrupted', 'Grants Level {N} Pride Skill', 'V2PrideSkillCorrupted', 1, 1, 21.00, 'corrupted', 56, 500, now64(3)),
    ('V2WrathSkillCorrupted', 'Grants Level {N} Wrath Skill', 'V2WrathSkillCorrupted', 1, 1, 21.00, 'corrupted', 45, 500, now64(3)),
    ('V2ZealotrySkillCorrupted_', 'Grants Level {N} Zealotry Skill', 'V2ZealotrySkillCorrupted', 1, 1, 23.00, 'corrupted', 56, 500, now64(3)),
    ('WeaponElementalDamage1', '({N}-{N})% increased Elemental Damage with Attack Skills', 'WeaponElementalDamage', 1, 5, 10.00, 'prefix', 4, 300, now64(3)),
    ('WeaponElementalDamage2', '({N}-{N})% increased Elemental Damage with Attack Skills', 'WeaponElementalDamage', 2, 5, 20.00, 'prefix', 15, 300, now64(3)),
    ('WeaponElementalDamage3', '({N}-{N})% increased Elemental Damage with Attack Skills', 'WeaponElementalDamage', 3, 5, 30.00, 'prefix', 30, 300, now64(3)),
    ('WeaponElementalDamage4', '({N}-{N})% increased Elemental Damage with Attack Skills', 'WeaponElementalDamage', 4, 5, 36.00, 'prefix', 60, 300, now64(3)),
    ('WeaponElementalDamage5', '({N}-{N})% increased Elemental Damage with Attack Skills', 'WeaponElementalDamage', 5, 5, 42.00, 'prefix', 81, 300, now64(3));

CREATE VIEW IF NOT EXISTS poe_trade.v_ml_v3_mirage_iron_ring_affix_catalog AS
SELECT
    mod_id,
    mod_text_pattern,
    mod_base_name,
    mod_tier,
    mod_max_tier,
    mod_max_value,
    mod_generation_type,
    required_level,
    ring_weight
FROM poe_trade.ml_ring_mod_catalog_v1
WHERE ring_weight > 0;

CREATE VIEW IF NOT EXISTS poe_trade.v_ml_v3_mirage_iron_ring_affix_rows AS
SELECT
    base.item_id AS item_id,
    base.item_name AS item_name,
    base.base_type AS base_type,
    base.ilvl AS ilvl,
    base.corrupted AS corrupted,
    base.fractured AS fractured,
    base.synthesised AS synthesised,
    toUInt8(ifNull(JSONExtractBool(base.item_json, 'mirrored'), 0)) AS mirrored,
    toUInt8(greatest(0, JSONExtractInt(base.item_json, 'quality'))) AS quality,
    JSONExtractArrayRaw(base.item_json, 'sockets') AS sockets_json,
    length(sockets_json) AS number_of_sockets,
    arrayCount(socket -> JSONExtractString(socket, 'sColour') = 'R', sockets_json) AS number_of_red_sockets,
    arrayCount(socket -> JSONExtractString(socket, 'sColour') = 'G', sockets_json) AS number_of_green_sockets,
    arrayCount(socket -> JSONExtractString(socket, 'sColour') = 'B', sockets_json) AS number_of_blue_sockets,
    arrayCount(socket -> JSONExtractString(socket, 'sColour') = 'W', sockets_json) AS number_of_white_sockets,
    if(
        empty(socket_groups),
        0,
        arrayMax(
            arrayMap(
                group_id -> countEqual(socket_groups, group_id),
                arrayDistinct(socket_groups)
            )
        )
    ) AS number_of_links,
    c.mod_id AS mod_id,
    c.mod_text_pattern AS mod_text_pattern,
    c.mod_base_name AS mod_base_name,
    c.mod_tier AS mod_tier,
    c.mod_max_tier AS mod_max_tier,
    c.mod_max_value AS mod_max_value,
    c.mod_generation_type AS mod_generation_type,
    c.required_level AS required_level,
    mod_line AS observed_mod_text,
    mod_value AS observed_value,
    if(c.mod_max_value > 0, greatest(0.0, least(100.0, (mod_value / c.mod_max_value) * 100.0)), 0.0) AS quality_roll_pct,
    base.observed_at AS observed_at
FROM
(
    SELECT
        base.as_of_ts AS observed_at,
        base.item_id AS item_id,
        base.item_name AS item_name,
        base.base_type AS base_type,
        base.ilvl AS ilvl,
        base.corrupted AS corrupted,
        base.fractured AS fractured,
        base.synthesised AS synthesised,
        obs.item_json AS item_json,
        JSONExtractArrayRaw(obs.item_json, 'sockets') AS sockets_json,
        arrayMap(socket -> toUInt8(JSONExtractInt(socket, 'group')), sockets_json) AS socket_groups,
        trimBoth(replaceAll(mod_line, '"', '')) AS normalized_mod_line,
        mod_line AS mod_line,
        if(empty(extractAll(mod_line, '\d+(?:\.\d+)?')), 0.0, arrayReduce('max', arrayMap(x -> toFloat64OrZero(x), extractAll(mod_line, '\d+(?:\.\d+)?')))) AS mod_value
    FROM poe_trade.v_ml_v3_iron_ring_training_poc AS base
    INNER JOIN poe_trade.silver_v3_item_observations AS obs
        ON obs.league = base.league
        AND obs.observed_at = base.as_of_ts
        AND ifNull(obs.item_id, concat(obs.stash_id, '|', obs.base_type, '|', toString(obs.observed_at))) = base.item_key
    ARRAY JOIN arrayConcat(
        JSONExtractArrayRaw(obs.item_json, 'implicitMods'),
        JSONExtractArrayRaw(obs.item_json, 'explicitMods'),
        JSONExtractArrayRaw(obs.item_json, 'enchantMods'),
        JSONExtractArrayRaw(obs.item_json, 'craftedMods'),
        JSONExtractArrayRaw(obs.item_json, 'fracturedMods')
    ) AS mod_line
) AS base
INNER JOIN poe_trade.ml_ring_mod_catalog_v1 AS c
    ON c.mod_text_pattern = base.normalized_mod_line
    AND c.ring_weight > 0
    AND c.mod_max_value >= base.mod_value
ORDER BY
    base.item_id,
    base.observed_at,
    base.normalized_mod_line,
    c.mod_max_value ASC,
    c.mod_tier DESC
LIMIT 1 BY
    base.item_id,
    base.observed_at,
    base.normalized_mod_line;
