CREATE OR REPLACE VIEW poe_trade.v_ml_v3_mirage_iron_ring_affix_rows_v1 AS
WITH
    arrayConcat(
        arrayMap(mod_line -> tuple('explicit', mod_line), JSONExtractArrayRaw(item.item_json, 'explicitMods')),
        arrayMap(mod_line -> tuple('implicit', mod_line), JSONExtractArrayRaw(item.item_json, 'implicitMods')),
        arrayMap(mod_line -> tuple('crafted', mod_line), JSONExtractArrayRaw(item.item_json, 'craftedMods')),
        arrayMap(mod_line -> tuple('fractured', mod_line), JSONExtractArrayRaw(item.item_json, 'fracturedMods')),
        arrayMap(mod_line -> tuple('enchant', mod_line), JSONExtractArrayRaw(item.item_json, 'enchantMods'))
    ) AS affix_tuples
SELECT
    item.observed_at,
    item.realm,
    item.league,
    item.stash_id,
    item.account_name,
    item.stash_name,
    item.checkpoint,
    item.next_change_id,
    item.item_id,
    item.identity_key,
    item.fingerprint_v3,
    item.item_name,
    item.item_type_line,
    item.base_type,
    item.rarity,
    item.category,
    item.ilvl,
    item.stack_size,
    item.corrupted,
    item.fractured,
    item.synthesised,
    item.note,
    item.forum_note,
    item.effective_price_note,
    item.parsed_amount,
    item.parsed_currency,
    item.normalized_affix_hash,
    tupleElement(affix_tuple, 1) AS affix_kind,
    tupleElement(affix_tuple, 2) AS affix_text
FROM poe_trade.ml_v3_mirage_iron_ring_branch_v1 AS item
ARRAY JOIN affix_tuples AS affix_tuple;

CREATE OR REPLACE VIEW poe_trade.v_ml_v3_mirage_iron_ring_item_features_v1 AS
SELECT
    observed_at,
    realm,
    league,
    stash_id,
    account_name,
    stash_name,
    checkpoint,
    next_change_id,
    item_id,
    identity_key,
    fingerprint_v3,
    item_name,
    item_type_line,
    base_type,
    rarity,
    category,
    ilvl,
    stack_size,
    corrupted,
    fractured,
    synthesised,
    note,
    forum_note,
    effective_price_note,
    parsed_amount,
    parsed_currency,
    normalized_affix_hash,
    count() AS affix_count,
    groupArray(tuple(affix_kind, affix_text)) AS affixes
FROM poe_trade.v_ml_v3_mirage_iron_ring_affix_rows_v1
GROUP BY
    observed_at,
    realm,
    league,
    stash_id,
    account_name,
    stash_name,
    checkpoint,
    next_change_id,
    item_id,
    identity_key,
    fingerprint_v3,
    item_name,
    item_type_line,
    base_type,
    rarity,
    category,
    ilvl,
    stack_size,
    corrupted,
    fractured,
    synthesised,
    note,
    forum_note,
    effective_price_note,
    parsed_amount,
    parsed_currency,
    normalized_affix_hash;
