INSERT INTO poe_trade.bronze_public_stash_mirage
WITH
item_base AS (
    SELECT
        base.ingested_at,
        base.realm,
        'Mirage' AS league,
        base.stash_id,
        nullIf(JSONExtractString(base.payload_json, 'id'), '') AS stash_json_id,
        base.checkpoint,
        base.next_change_id,
        nullIf(JSONExtractString(base.payload_json, 'accountName'), '') AS account_name,
        nullIf(JSONExtractString(base.payload_json, 'stash'), '') AS stash_name,
        nullIf(JSONExtractString(base.payload_json, 'stashType'), '') AS stash_type,
        toUInt8(ifNull(JSONExtractBool(base.payload_json, 'public'), 1)) AS public_flag,
        toUInt32(item_index) AS root_item_ordinal,
        nullIf(JSONExtractString(item_json, 'id'), '') AS root_item_id,
        nullIf(JSONExtractString(item_json, 'id'), '') AS item_id,
        nullIf(JSONExtractString(item_json, 'league'), '') AS item_league,
        nullIf(JSONExtractString(item_json, 'name'), '') AS item_name,
        nullIf(JSONExtractString(item_json, 'typeLine'), '') AS item_type_line,
        nullIf(JSONExtractString(item_json, 'baseType'), '') AS base_type,
        nullIf(JSONExtractString(item_json, 'rarity'), '') AS rarity,
        nullIf(JSONExtractString(item_json, 'inventoryId'), '') AS inventory_id,
        nullIf(JSONExtractString(item_json, 'note'), '') AS note,
        nullIf(JSONExtractString(item_json, 'forum_note'), '') AS forum_note,
        nullIf(JSONExtractString(item_json, 'icon'), '') AS icon,
        nullIf(JSONExtractString(item_json, 'descrText'), '') AS descr_text,
        nullIf(JSONExtractString(item_json, 'secDescrText'), '') AS sec_descr_text,
        nullIf(JSONExtractString(item_json, 'artFilename'), '') AS art_filename,
        nullIf(JSONExtractString(item_json, 'builtInSupport'), '') AS built_in_support,
        nullIf(JSONExtractString(item_json, 'colour'), '') AS item_colour,
        nullIf(JSONExtractString(item_json, 'stackSizeText'), '') AS stack_size_text,
        if(JSONHas(item_json, 'ilvl'), toUInt16(greatest(0, JSONExtractInt(item_json, 'ilvl'))), NULL) AS ilvl,
        if(JSONHas(item_json, 'itemLevel'), toUInt16(greatest(0, JSONExtractInt(item_json, 'itemLevel'))), NULL) AS item_level,
        if(JSONHas(item_json, 'monsterLevel'), toUInt16(greatest(0, JSONExtractInt(item_json, 'monsterLevel'))), NULL) AS monster_level,
        if(JSONHas(item_json, 'stackSize'), toUInt32(greatest(0, JSONExtractInt(item_json, 'stackSize'))), NULL) AS stack_size,
        if(JSONHas(item_json, 'maxStackSize'), toUInt32(greatest(0, JSONExtractInt(item_json, 'maxStackSize'))), NULL) AS max_stack_size,
        if(JSONHas(item_json, 'frameType'), toUInt8(greatest(0, JSONExtractInt(item_json, 'frameType'))), NULL) AS frame_type,
        if(JSONHas(item_json, 'w'), toUInt8(greatest(0, JSONExtractInt(item_json, 'w'))), NULL) AS w,
        if(JSONHas(item_json, 'h'), toUInt8(greatest(0, JSONExtractInt(item_json, 'h'))), NULL) AS h,
        if(JSONHas(item_json, 'x'), toUInt8(greatest(0, JSONExtractInt(item_json, 'x'))), NULL) AS x,
        if(JSONHas(item_json, 'y'), toUInt8(greatest(0, JSONExtractInt(item_json, 'y'))), NULL) AS y,
        if(JSONHas(item_json, 'socket'), toUInt8(greatest(0, JSONExtractInt(item_json, 'socket'))), NULL) AS socket_index,
        if(JSONHas(item_json, 'talismanTier'), toUInt8(greatest(0, JSONExtractInt(item_json, 'talismanTier'))), NULL) AS talisman_tier,
        if(JSONHas(item_json, 'foilVariation'), toUInt16(greatest(0, JSONExtractInt(item_json, 'foilVariation'))), NULL) AS foil_variation,
        if(JSONHas(item_json, 'verified'), toUInt8(JSONExtractBool(item_json, 'verified')), NULL) AS verified,
        if(JSONHas(item_json, 'identified'), toUInt8(JSONExtractBool(item_json, 'identified')), NULL) AS identified,
        if(JSONHas(item_json, 'corrupted'), toUInt8(JSONExtractBool(item_json, 'corrupted')), NULL) AS corrupted,
        if(JSONHas(item_json, 'fractured'), toUInt8(JSONExtractBool(item_json, 'fractured')), NULL) AS fractured,
        if(JSONHas(item_json, 'synthesised'), toUInt8(JSONExtractBool(item_json, 'synthesised')), NULL) AS synthesised,
        if(JSONHas(item_json, 'duplicated'), toUInt8(JSONExtractBool(item_json, 'duplicated')), NULL) AS duplicated,
        if(JSONHas(item_json, 'split'), toUInt8(JSONExtractBool(item_json, 'split')), NULL) AS split_flag,
        if(JSONHas(item_json, 'support'), toUInt8(JSONExtractBool(item_json, 'support')), NULL) AS support_flag,
        if(JSONHas(item_json, 'abyssJewel'), toUInt8(JSONExtractBool(item_json, 'abyssJewel')), NULL) AS abyss_jewel,
        if(JSONHas(item_json, 'delve'), toUInt8(JSONExtractBool(item_json, 'delve')), NULL) AS delve,
        if(JSONHas(item_json, 'elder'), toUInt8(JSONExtractBool(item_json, 'elder')), NULL) AS elder,
        if(JSONHas(item_json, 'shaper'), toUInt8(JSONExtractBool(item_json, 'shaper')), NULL) AS shaper,
        if(JSONHas(item_json, 'searing'), toUInt8(JSONExtractBool(item_json, 'searing')), NULL) AS searing,
        if(JSONHas(item_json, 'tangled'), toUInt8(JSONExtractBool(item_json, 'tangled')), NULL) AS tangled,
        if(JSONHas(item_json, 'veiled'), toUInt8(JSONExtractBool(item_json, 'veiled')), NULL) AS veiled,
        if(JSONHas(item_json, 'memoryItem'), toUInt8(JSONExtractBool(item_json, 'memoryItem')), NULL) AS memory_item,
        if(JSONHas(item_json, 'mutated'), toUInt8(JSONExtractBool(item_json, 'mutated')), NULL) AS mutated,
        if(JSONHas(item_json, 'unmodifiable'), toUInt8(JSONExtractBool(item_json, 'unmodifiable')), NULL) AS unmodifiable,
        if(JSONHas(item_json, 'unmodifiableExceptChaos'), toUInt8(JSONExtractBool(item_json, 'unmodifiableExceptChaos')), NULL) AS unmodifiable_except_chaos,
        if(JSONHas(item_json, 'isRelic'), toUInt8(JSONExtractBool(item_json, 'isRelic')), NULL) AS is_relic,
        if(JSONHas(item_json, 'replica'), toUInt8(JSONExtractBool(item_json, 'replica')), NULL) AS replica,
        if(JSONHas(JSONExtractRaw(item_json, 'extended'), 'prefixes'), toUInt8(greatest(0, JSONExtractInt(JSONExtractRaw(item_json, 'extended'), 'prefixes'))), NULL) AS extended_prefixes,
        if(JSONHas(JSONExtractRaw(item_json, 'extended'), 'suffixes'), toUInt8(greatest(0, JSONExtractInt(JSONExtractRaw(item_json, 'extended'), 'suffixes'))), NULL) AS extended_suffixes,
        nullIf(JSONExtractString(JSONExtractRaw(item_json, 'hybrid'), 'baseTypeName'), '') AS hybrid_base_type_name,
        if(JSONHas(JSONExtractRaw(item_json, 'hybrid'), 'isVaalGem'), toUInt8(JSONExtractBool(JSONExtractRaw(item_json, 'hybrid'), 'isVaalGem')), NULL) AS hybrid_is_vaal_gem,
        nullIf(JSONExtractString(JSONExtractRaw(item_json, 'hybrid'), 'secDescrText'), '') AS hybrid_sec_descr_text,
        nullIf(JSONExtractString(JSONExtractRaw(item_json, 'incubatedItem'), 'name'), '') AS incubated_item_name,
        if(JSONHas(JSONExtractRaw(item_json, 'incubatedItem'), 'level'), toUInt16(greatest(0, JSONExtractInt(JSONExtractRaw(item_json, 'incubatedItem'), 'level'))), NULL) AS incubated_item_level,
        if(JSONHas(JSONExtractRaw(item_json, 'incubatedItem'), 'progress'), toUInt32(greatest(0, JSONExtractInt(JSONExtractRaw(item_json, 'incubatedItem'), 'progress'))), NULL) AS incubated_item_progress,
        if(JSONHas(JSONExtractRaw(item_json, 'incubatedItem'), 'total'), toUInt32(greatest(0, JSONExtractInt(JSONExtractRaw(item_json, 'incubatedItem'), 'total'))), NULL) AS incubated_item_total,
        if(JSONHas(JSONExtractRaw(item_json, 'influences'), 'crusader'), toUInt8(JSONExtractBool(JSONExtractRaw(item_json, 'influences'), 'crusader')), NULL) AS influence_crusader,
        if(JSONHas(JSONExtractRaw(item_json, 'influences'), 'elder'), toUInt8(JSONExtractBool(JSONExtractRaw(item_json, 'influences'), 'elder')), NULL) AS influence_elder,
        if(JSONHas(JSONExtractRaw(item_json, 'influences'), 'hunter'), toUInt8(JSONExtractBool(JSONExtractRaw(item_json, 'influences'), 'hunter')), NULL) AS influence_hunter,
        if(JSONHas(JSONExtractRaw(item_json, 'influences'), 'redeemer'), toUInt8(JSONExtractBool(JSONExtractRaw(item_json, 'influences'), 'redeemer')), NULL) AS influence_redeemer,
        if(JSONHas(JSONExtractRaw(item_json, 'influences'), 'shaper'), toUInt8(JSONExtractBool(JSONExtractRaw(item_json, 'influences'), 'shaper')), NULL) AS influence_shaper,
        if(JSONHas(JSONExtractRaw(item_json, 'influences'), 'warlord'), toUInt8(JSONExtractBool(JSONExtractRaw(item_json, 'influences'), 'warlord')), NULL) AS influence_warlord,
        item_json
    FROM poe_trade.raw_public_stash_pages AS base
    ARRAY JOIN
        arrayEnumerate(JSONExtractArrayRaw(base.payload_json, 'items')) AS item_index,
        JSONExtractArrayRaw(base.payload_json, 'items') AS item_json
    WHERE base.league = 'Mirage'
)
SELECT
    ingested_at, realm, league, stash_id, stash_json_id, checkpoint, next_change_id,
    account_name, stash_name, stash_type, public_flag,
    'item' AS row_type,
    CAST(NULL AS Nullable(String)) AS array_group,
    root_item_ordinal, root_item_id, item_id,
    CAST(NULL AS Nullable(String)) AS parent_item_id,
    CAST(NULL AS Nullable(UInt32)) AS array_ordinal,
    CAST(NULL AS Nullable(UInt32)) AS value_ordinal,
    item_league, item_name, item_type_line, base_type, rarity, inventory_id, note,
    forum_note, icon, descr_text, sec_descr_text, art_filename, built_in_support,
    item_colour, stack_size_text, ilvl, item_level, monster_level, stack_size,
    max_stack_size, frame_type, w, h, x, y, socket_index,
    CAST(NULL AS Nullable(UInt8)) AS socket_group,
    CAST(NULL AS Nullable(String)) AS socket_attr,
    CAST(NULL AS Nullable(String)) AS socket_colour,
    talisman_tier, foil_variation, verified, identified, corrupted, fractured,
    synthesised, duplicated, split_flag, support_flag, abyss_jewel, delve, elder,
    shaper, searing, tangled, veiled, memory_item, mutated, unmodifiable,
    unmodifiable_except_chaos, is_relic, replica, extended_prefixes,
    extended_suffixes, hybrid_base_type_name, hybrid_is_vaal_gem,
    hybrid_sec_descr_text, incubated_item_name, incubated_item_level,
    incubated_item_progress, incubated_item_total, influence_crusader,
    influence_elder, influence_hunter, influence_redeemer, influence_shaper,
    influence_warlord,
    CAST(NULL AS Nullable(String)) AS attribute_name,
    CAST(NULL AS Nullable(Int32)) AS attribute_display_mode,
    CAST(NULL AS Nullable(Int32)) AS attribute_type,
    CAST(NULL AS Nullable(String)) AS attribute_suffix,
    CAST(NULL AS Nullable(Float64)) AS attribute_progress,
    CAST(NULL AS Nullable(String)) AS attribute_value_text,
    CAST(NULL AS Nullable(Int32)) AS attribute_value_style,
    CAST(NULL AS Nullable(String)) AS mod_text,
    CAST(NULL AS Nullable(String)) AS logbook_name,
    CAST(NULL AS Nullable(String)) AS logbook_faction_id,
    CAST(NULL AS Nullable(String)) AS logbook_faction_name,
    CAST(NULL AS Nullable(String)) AS ultimatum_type,
    CAST(NULL AS Nullable(UInt8)) AS ultimatum_tier
FROM item_base;
