CREATE TABLE IF NOT EXISTS poe_trade.silver_items (
    observed_at DateTime64(3, 'UTC') CODEC(Delta(8), ZSTD(3)),
    checkpoint String CODEC(ZSTD(3)),
    root_item_id String CODEC(ZSTD(3)),
    stash_id String CODEC(ZSTD(3)),
    account_name Nullable(String) CODEC(ZSTD(3)),
    stash_name Nullable(String) CODEC(ZSTD(3)),
    stash_type LowCardinality(Nullable(String)),
    root_item_ordinal UInt32,
    item_name Nullable(String) CODEC(ZSTD(3)),
    item_type_line Nullable(String) CODEC(ZSTD(3)),
    base_type Nullable(String) CODEC(ZSTD(3)),
    rarity LowCardinality(Nullable(String)),
    inventory_id Nullable(String) CODEC(ZSTD(3)),
    note Nullable(String) CODEC(ZSTD(3)),
    effective_price_note Nullable(String) CODEC(ZSTD(3)),
    parsed_price_amount Nullable(Float64),
    parsed_price_currency Nullable(String) CODEC(ZSTD(3)),
    icon Nullable(String) CODEC(ZSTD(3)),
    descr_text Nullable(String) CODEC(ZSTD(3)),
    sec_descr_text Nullable(String) CODEC(ZSTD(3)),
    art_filename Nullable(String) CODEC(ZSTD(3)),
    built_in_support Nullable(String) CODEC(ZSTD(3)),
    item_colour LowCardinality(Nullable(String)),
    stack_size_text Nullable(String) CODEC(ZSTD(3)),
    ilvl Nullable(UInt16),
    item_level Nullable(UInt16),
    monster_level Nullable(UInt16),
    stack_size Nullable(UInt32),
    max_stack_size Nullable(UInt32),
    frame_type Nullable(UInt8),
    w Nullable(UInt8),
    h Nullable(UInt8),
    x Nullable(UInt8),
    y Nullable(UInt8),
    socket_index Nullable(UInt8),
    talisman_tier Nullable(UInt8),
    foil_variation Nullable(UInt16),
    verified Nullable(UInt8),
    identified Nullable(UInt8),
    corrupted Nullable(UInt8),
    fractured Nullable(UInt8),
    synthesised Nullable(UInt8),
    duplicated Nullable(UInt8),
    split_flag Nullable(UInt8),
    support_flag Nullable(UInt8),
    abyss_jewel Nullable(UInt8),
    delve Nullable(UInt8),
    elder Nullable(UInt8),
    shaper Nullable(UInt8),
    searing Nullable(UInt8),
    tangled Nullable(UInt8),
    veiled Nullable(UInt8),
    memory_item Nullable(UInt8),
    mutated Nullable(UInt8),
    unmodifiable Nullable(UInt8),
    unmodifiable_except_chaos Nullable(UInt8),
    is_relic Nullable(UInt8),
    replica Nullable(UInt8),
    extended_prefixes Nullable(UInt8),
    extended_suffixes Nullable(UInt8),
    hybrid_base_type_name Nullable(String) CODEC(ZSTD(3)),
    hybrid_is_vaal_gem Nullable(UInt8),
    hybrid_sec_descr_text Nullable(String) CODEC(ZSTD(3)),
    incubated_item_name Nullable(String) CODEC(ZSTD(3)),
    incubated_item_level Nullable(UInt16),
    incubated_item_progress Nullable(UInt32),
    incubated_item_total Nullable(UInt32),
    influence_crusader Nullable(UInt8),
    influence_elder Nullable(UInt8),
    influence_hunter Nullable(UInt8),
    influence_redeemer Nullable(UInt8),
    influence_shaper Nullable(UInt8),
    influence_warlord Nullable(UInt8),
    properties Array(Tuple(
        array_ordinal UInt32,
        value_ordinal UInt32,
        attribute_name Nullable(String),
        attribute_display_mode Nullable(Int32),
        attribute_type Nullable(Int32),
        attribute_suffix Nullable(String),
        attribute_progress Nullable(Float64),
        attribute_value_text Nullable(String),
        attribute_value_style Nullable(Int32))) CODEC(ZSTD(3)),
    requirements Array(Tuple(
        array_ordinal UInt32,
        value_ordinal UInt32,
        attribute_name Nullable(String),
        attribute_display_mode Nullable(Int32),
        attribute_type Nullable(Int32),
        attribute_suffix Nullable(String),
        attribute_progress Nullable(Float64),
        attribute_value_text Nullable(String),
        attribute_value_style Nullable(Int32))) CODEC(ZSTD(3)),
    additional_properties Array(Tuple(
        array_ordinal UInt32,
        value_ordinal UInt32,
        attribute_name Nullable(String),
        attribute_display_mode Nullable(Int32),
        attribute_type Nullable(Int32),
        attribute_suffix Nullable(String),
        attribute_progress Nullable(Float64),
        attribute_value_text Nullable(String),
        attribute_value_style Nullable(Int32))) CODEC(ZSTD(3)),
    next_level_requirements Array(Tuple(
        array_ordinal UInt32,
        value_ordinal UInt32,
        attribute_name Nullable(String),
        attribute_display_mode Nullable(Int32),
        attribute_type Nullable(Int32),
        attribute_suffix Nullable(String),
        attribute_progress Nullable(Float64),
        attribute_value_text Nullable(String),
        attribute_value_style Nullable(Int32))) CODEC(ZSTD(3)),
    hybrid_properties Array(Tuple(
        array_ordinal UInt32,
        value_ordinal UInt32,
        attribute_name Nullable(String),
        attribute_display_mode Nullable(Int32),
        attribute_type Nullable(Int32),
        attribute_suffix Nullable(String),
        attribute_progress Nullable(Float64),
        attribute_value_text Nullable(String),
        attribute_value_style Nullable(Int32))) CODEC(ZSTD(3)),
    explicit_mods Array(String) CODEC(ZSTD(3)),
    implicit_mods Array(String) CODEC(ZSTD(3)),
    enchant_mods Array(String) CODEC(ZSTD(3)),
    fractured_mods Array(String) CODEC(ZSTD(3)),
    crafted_mods Array(String) CODEC(ZSTD(3)),
    utility_mods Array(String) CODEC(ZSTD(3)),
    veiled_mods Array(String) CODEC(ZSTD(3)),
    flavour_text_lines Array(String) CODEC(ZSTD(3)),
    mutated_mods Array(String) CODEC(ZSTD(3)),
    hybrid_explicit_mods Array(String) CODEC(ZSTD(3)),
    sockets Array(Tuple(
        array_ordinal UInt32,
        socket_group Nullable(UInt8),
        socket_attr Nullable(String),
        socket_colour Nullable(String))) CODEC(ZSTD(3)),
    ultimatum_mods Array(Tuple(
        array_ordinal UInt32,
        ultimatum_type Nullable(String),
        ultimatum_tier Nullable(UInt8))) CODEC(ZSTD(3)),
    logbook_mods Array(Tuple(
        array_ordinal UInt32,
        value_ordinal UInt32,
        logbook_name Nullable(String),
        logbook_faction_id Nullable(String),
        logbook_faction_name Nullable(String),
        mod_text Nullable(String))) CODEC(ZSTD(3)),
    socketed_items Array(Tuple(
        socketed_item_ordinal UInt32,
        item_id Nullable(String),
        item_name Nullable(String),
        item_type_line Nullable(String),
        base_type Nullable(String),
        rarity Nullable(String),
        inventory_id Nullable(String),
        note Nullable(String),
        icon Nullable(String),
        ilvl Nullable(UInt16),
        stack_size Nullable(UInt32),
        frame_type Nullable(UInt8),
        socket_index Nullable(UInt8),
        verified Nullable(UInt8),
        identified Nullable(UInt8),
        corrupted Nullable(UInt8),
        fractured Nullable(UInt8))) CODEC(ZSTD(3)),
    socketed_item_properties Array(Tuple(
        socketed_item_id Nullable(String),
        array_group Nullable(String),
        array_ordinal UInt32,
        value_ordinal UInt32,
        attribute_name Nullable(String),
        attribute_display_mode Nullable(Int32),
        attribute_type Nullable(Int32),
        attribute_suffix Nullable(String),
        attribute_progress Nullable(Float64),
        attribute_value_text Nullable(String),
        attribute_value_style Nullable(Int32))) CODEC(ZSTD(3)),
    socketed_item_mods Array(Tuple(
        socketed_item_id Nullable(String),
        mod_group Nullable(String),
        array_ordinal UInt32,
        mod_text Nullable(String))) CODEC(ZSTD(3))
) ENGINE = ReplacingMergeTree(observed_at)
PARTITION BY toYYYYMMDD(observed_at)
ORDER BY (checkpoint, root_item_id)
SETTINGS index_granularity = 8192;

CREATE MATERIALIZED VIEW IF NOT EXISTS poe_trade.mv_bronze_public_stash_mirage_to_silver_items
TO poe_trade.silver_items AS
WITH aggregated AS (
    SELECT
        checkpoint,
        root_item_id,
        maxIf(ingested_at, row_type = 'item') AS observed_at,
        argMaxIf(stash_id, ingested_at, row_type = 'item') AS stash_id,
        argMaxIf(account_name, ingested_at, row_type = 'item') AS account_name,
        argMaxIf(stash_name, ingested_at, row_type = 'item') AS stash_name,
        argMaxIf(stash_type, ingested_at, row_type = 'item') AS stash_type,
        maxIf(root_item_ordinal, row_type = 'item') AS root_item_ordinal,
        argMaxIf(item_name, ingested_at, row_type = 'item') AS root_item_name,
        argMaxIf(item_type_line, ingested_at, row_type = 'item') AS root_item_type_line,
        argMaxIf(base_type, ingested_at, row_type = 'item') AS root_base_type,
        argMaxIf(rarity, ingested_at, row_type = 'item') AS root_rarity,
        argMaxIf(inventory_id, ingested_at, row_type = 'item') AS root_inventory_id,
        argMaxIf(note, ingested_at, row_type = 'item') AS root_note,
        argMaxIf(icon, ingested_at, row_type = 'item') AS root_icon,
        argMaxIf(descr_text, ingested_at, row_type = 'item') AS descr_text,
        argMaxIf(sec_descr_text, ingested_at, row_type = 'item') AS sec_descr_text,
        argMaxIf(art_filename, ingested_at, row_type = 'item') AS art_filename,
        argMaxIf(built_in_support, ingested_at, row_type = 'item') AS built_in_support,
        argMaxIf(item_colour, ingested_at, row_type = 'item') AS item_colour,
        argMaxIf(stack_size_text, ingested_at, row_type = 'item') AS stack_size_text,
        argMaxIf(ilvl, ingested_at, row_type = 'item') AS root_ilvl,
        argMaxIf(item_level, ingested_at, row_type = 'item') AS item_level,
        argMaxIf(monster_level, ingested_at, row_type = 'item') AS monster_level,
        argMaxIf(stack_size, ingested_at, row_type = 'item') AS root_stack_size,
        argMaxIf(max_stack_size, ingested_at, row_type = 'item') AS max_stack_size,
        argMaxIf(frame_type, ingested_at, row_type = 'item') AS root_frame_type,
        argMaxIf(w, ingested_at, row_type = 'item') AS w,
        argMaxIf(h, ingested_at, row_type = 'item') AS h,
        argMaxIf(x, ingested_at, row_type = 'item') AS x,
        argMaxIf(y, ingested_at, row_type = 'item') AS y,
        argMaxIf(socket_index, ingested_at, row_type = 'item') AS root_socket_index,
        argMaxIf(talisman_tier, ingested_at, row_type = 'item') AS talisman_tier,
        argMaxIf(foil_variation, ingested_at, row_type = 'item') AS foil_variation,
        argMaxIf(verified, ingested_at, row_type = 'item') AS root_verified,
        argMaxIf(identified, ingested_at, row_type = 'item') AS root_identified,
        argMaxIf(corrupted, ingested_at, row_type = 'item') AS root_corrupted,
        argMaxIf(fractured, ingested_at, row_type = 'item') AS root_fractured,
        argMaxIf(synthesised, ingested_at, row_type = 'item') AS synthesised,
        argMaxIf(duplicated, ingested_at, row_type = 'item') AS duplicated,
        argMaxIf(split_flag, ingested_at, row_type = 'item') AS split_flag,
        argMaxIf(support_flag, ingested_at, row_type = 'item') AS support_flag,
        argMaxIf(abyss_jewel, ingested_at, row_type = 'item') AS abyss_jewel,
        argMaxIf(delve, ingested_at, row_type = 'item') AS delve,
        argMaxIf(elder, ingested_at, row_type = 'item') AS elder,
        argMaxIf(shaper, ingested_at, row_type = 'item') AS shaper,
        argMaxIf(searing, ingested_at, row_type = 'item') AS searing,
        argMaxIf(tangled, ingested_at, row_type = 'item') AS tangled,
        argMaxIf(veiled, ingested_at, row_type = 'item') AS veiled,
        argMaxIf(memory_item, ingested_at, row_type = 'item') AS memory_item,
        argMaxIf(mutated, ingested_at, row_type = 'item') AS mutated,
        argMaxIf(unmodifiable, ingested_at, row_type = 'item') AS unmodifiable,
        argMaxIf(unmodifiable_except_chaos, ingested_at, row_type = 'item') AS unmodifiable_except_chaos,
        argMaxIf(is_relic, ingested_at, row_type = 'item') AS is_relic,
        argMaxIf(replica, ingested_at, row_type = 'item') AS replica,
        argMaxIf(extended_prefixes, ingested_at, row_type = 'item') AS extended_prefixes,
        argMaxIf(extended_suffixes, ingested_at, row_type = 'item') AS extended_suffixes,
        argMaxIf(hybrid_base_type_name, ingested_at, row_type = 'item') AS hybrid_base_type_name,
        argMaxIf(hybrid_is_vaal_gem, ingested_at, row_type = 'item') AS hybrid_is_vaal_gem,
        argMaxIf(hybrid_sec_descr_text, ingested_at, row_type = 'item') AS hybrid_sec_descr_text,
        argMaxIf(incubated_item_name, ingested_at, row_type = 'item') AS incubated_item_name,
        argMaxIf(incubated_item_level, ingested_at, row_type = 'item') AS incubated_item_level,
        argMaxIf(incubated_item_progress, ingested_at, row_type = 'item') AS incubated_item_progress,
        argMaxIf(incubated_item_total, ingested_at, row_type = 'item') AS incubated_item_total,
        argMaxIf(influence_crusader, ingested_at, row_type = 'item') AS influence_crusader,
        argMaxIf(influence_elder, ingested_at, row_type = 'item') AS influence_elder,
        argMaxIf(influence_hunter, ingested_at, row_type = 'item') AS influence_hunter,
        argMaxIf(influence_redeemer, ingested_at, row_type = 'item') AS influence_redeemer,
        argMaxIf(influence_shaper, ingested_at, row_type = 'item') AS influence_shaper,
        argMaxIf(influence_warlord, ingested_at, row_type = 'item') AS influence_warlord,
        arraySort(x -> (x.1, x.2), groupUniqArrayIf((toUInt32(ifNull(array_ordinal, 0)), toUInt32(ifNull(value_ordinal, 0)), attribute_name, attribute_display_mode, attribute_type, attribute_suffix, attribute_progress, attribute_value_text, attribute_value_style), (row_type = 'item_attribute') AND (array_group = 'properties'))) AS properties,
        arraySort(x -> (x.1, x.2), groupUniqArrayIf((toUInt32(ifNull(array_ordinal, 0)), toUInt32(ifNull(value_ordinal, 0)), attribute_name, attribute_display_mode, attribute_type, attribute_suffix, attribute_progress, attribute_value_text, attribute_value_style), (row_type = 'item_attribute') AND (array_group = 'requirements'))) AS requirements,
        arraySort(x -> (x.1, x.2), groupUniqArrayIf((toUInt32(ifNull(array_ordinal, 0)), toUInt32(ifNull(value_ordinal, 0)), attribute_name, attribute_display_mode, attribute_type, attribute_suffix, attribute_progress, attribute_value_text, attribute_value_style), (row_type = 'item_attribute') AND (array_group = 'additionalProperties'))) AS additional_properties,
        arraySort(x -> (x.1, x.2), groupUniqArrayIf((toUInt32(ifNull(array_ordinal, 0)), toUInt32(ifNull(value_ordinal, 0)), attribute_name, attribute_display_mode, attribute_type, attribute_suffix, attribute_progress, attribute_value_text, attribute_value_style), (row_type = 'item_attribute') AND (array_group = 'nextLevelRequirements'))) AS next_level_requirements,
        arraySort(x -> (x.1, x.2), groupUniqArrayIf((toUInt32(ifNull(array_ordinal, 0)), toUInt32(ifNull(value_ordinal, 0)), attribute_name, attribute_display_mode, attribute_type, attribute_suffix, attribute_progress, attribute_value_text, attribute_value_style), (row_type = 'item_attribute') AND (array_group = 'hybrid.properties'))) AS hybrid_properties,
        arrayMap(x -> (x.2), arraySort(x -> (x.1), groupUniqArrayIf((toUInt32(ifNull(array_ordinal, 0)), mod_text), (row_type = 'item_mod') AND (array_group = 'explicitMods') AND (mod_text IS NOT NULL)))) AS explicit_mods,
        arrayMap(x -> (x.2), arraySort(x -> (x.1), groupUniqArrayIf((toUInt32(ifNull(array_ordinal, 0)), mod_text), (row_type = 'item_mod') AND (array_group = 'implicitMods') AND (mod_text IS NOT NULL)))) AS implicit_mods,
        arrayMap(x -> (x.2), arraySort(x -> (x.1), groupUniqArrayIf((toUInt32(ifNull(array_ordinal, 0)), mod_text), (row_type = 'item_mod') AND (array_group = 'enchantMods') AND (mod_text IS NOT NULL)))) AS enchant_mods,
        arrayMap(x -> (x.2), arraySort(x -> (x.1), groupUniqArrayIf((toUInt32(ifNull(array_ordinal, 0)), mod_text), (row_type = 'item_mod') AND (array_group = 'fracturedMods') AND (mod_text IS NOT NULL)))) AS fractured_mods,
        arrayMap(x -> (x.2), arraySort(x -> (x.1), groupUniqArrayIf((toUInt32(ifNull(array_ordinal, 0)), mod_text), (row_type = 'item_mod') AND (array_group = 'craftedMods') AND (mod_text IS NOT NULL)))) AS crafted_mods,
        arrayMap(x -> (x.2), arraySort(x -> (x.1), groupUniqArrayIf((toUInt32(ifNull(array_ordinal, 0)), mod_text), (row_type = 'item_mod') AND (array_group = 'utilityMods') AND (mod_text IS NOT NULL)))) AS utility_mods,
        arrayMap(x -> (x.2), arraySort(x -> (x.1), groupUniqArrayIf((toUInt32(ifNull(array_ordinal, 0)), mod_text), (row_type = 'item_mod') AND (array_group = 'veiledMods') AND (mod_text IS NOT NULL)))) AS veiled_mods,
        arrayMap(x -> (x.2), arraySort(x -> (x.1), groupUniqArrayIf((toUInt32(ifNull(array_ordinal, 0)), mod_text), (row_type = 'item_mod') AND (array_group = 'flavourText') AND (mod_text IS NOT NULL)))) AS flavour_text_lines,
        arrayMap(x -> (x.2), arraySort(x -> (x.1), groupUniqArrayIf((toUInt32(ifNull(array_ordinal, 0)), mod_text), (row_type = 'item_mod') AND (array_group = 'mutatedMods') AND (mod_text IS NOT NULL)))) AS mutated_mods,
        arrayMap(x -> (x.2), arraySort(x -> (x.1), groupUniqArrayIf((toUInt32(ifNull(array_ordinal, 0)), mod_text), (row_type = 'item_mod') AND (array_group = 'hybrid.explicitMods') AND (mod_text IS NOT NULL)))) AS hybrid_explicit_mods,
        arraySort(x -> (x.1), groupUniqArrayIf((toUInt32(ifNull(array_ordinal, 0)), socket_group, socket_attr, socket_colour), row_type = 'item_socket')) AS sockets,
        arraySort(x -> (x.1), groupUniqArrayIf((toUInt32(ifNull(array_ordinal, 0)), ultimatum_type, ultimatum_tier), row_type = 'item_ultimatum_mod')) AS ultimatum_mods,
        arraySort(x -> (x.1, x.2), groupUniqArrayIf((toUInt32(ifNull(array_ordinal, 0)), toUInt32(ifNull(value_ordinal, 0)), logbook_name, logbook_faction_id, logbook_faction_name, mod_text), row_type = 'item_logbook_mod')) AS logbook_mods,
        arraySort(x -> (x.1), groupUniqArrayIf((toUInt32(ifNull(array_ordinal, 0)), item_id, item_name, item_type_line, base_type, rarity, inventory_id, note, icon, ilvl, stack_size, frame_type, socket_index, verified, identified, corrupted, fractured), row_type = 'socketed_item')) AS socketed_items,
        arraySort(x -> (x.1, x.2, x.3, x.4), groupUniqArrayIf((item_id, array_group, toUInt32(ifNull(array_ordinal, 0)), toUInt32(ifNull(value_ordinal, 0)), attribute_name, attribute_display_mode, attribute_type, attribute_suffix, attribute_progress, attribute_value_text, attribute_value_style), row_type = 'socketed_item_attribute')) AS socketed_item_properties,
        arraySort(x -> (x.1, x.2, x.3), groupUniqArrayIf((item_id, array_group, toUInt32(ifNull(array_ordinal, 0)), mod_text), (row_type = 'socketed_item_mod') AND (mod_text IS NOT NULL))) AS socketed_item_mods
    FROM poe_trade.bronze_public_stash_mirage
    WHERE root_item_id IS NOT NULL
    GROUP BY
        checkpoint,
        root_item_id
)
SELECT
    observed_at,
    checkpoint,
    root_item_id,
    stash_id,
    account_name,
    stash_name,
    stash_type,
    root_item_ordinal,
    root_item_name AS item_name,
    root_item_type_line AS item_type_line,
    root_base_type AS base_type,
    root_rarity AS rarity,
    root_inventory_id AS inventory_id,
    root_note AS note,
    coalesce(root_note, if(match(ifNull(stash_name, ''), '^~'), stash_name, NULL)) AS effective_price_note,
    toFloat64OrNull(extract(coalesce(root_note, if(match(ifNull(stash_name, ''), '^~'), stash_name, '')), '^~(?:b/o|price)\\s+([0-9]+(?:\\.[0-9]+)?)')) AS parsed_price_amount,
    nullIf(extract(coalesce(root_note, if(match(ifNull(stash_name, ''), '^~'), stash_name, '')), '^~(?:b/o|price)\\s+[0-9]+(?:\\.[0-9]+)?\\s+(.+)$'), '') AS parsed_price_currency,
    root_icon AS icon,
    descr_text,
    sec_descr_text,
    art_filename,
    built_in_support,
    item_colour,
    stack_size_text,
    root_ilvl AS ilvl,
    item_level,
    monster_level,
    root_stack_size AS stack_size,
    max_stack_size,
    root_frame_type AS frame_type,
    w,
    h,
    x,
    y,
    root_socket_index AS socket_index,
    talisman_tier,
    foil_variation,
    root_verified AS verified,
    root_identified AS identified,
    root_corrupted AS corrupted,
    root_fractured AS fractured,
    synthesised,
    duplicated,
    split_flag,
    support_flag,
    abyss_jewel,
    delve,
    elder,
    shaper,
    searing,
    tangled,
    veiled,
    memory_item,
    mutated,
    unmodifiable,
    unmodifiable_except_chaos,
    is_relic,
    replica,
    extended_prefixes,
    extended_suffixes,
    hybrid_base_type_name,
    hybrid_is_vaal_gem,
    hybrid_sec_descr_text,
    incubated_item_name,
    incubated_item_level,
    incubated_item_progress,
    incubated_item_total,
    influence_crusader,
    influence_elder,
    influence_hunter,
    influence_redeemer,
    influence_shaper,
    influence_warlord,
    properties,
    requirements,
    additional_properties,
    next_level_requirements,
    hybrid_properties,
    explicit_mods,
    implicit_mods,
    enchant_mods,
    fractured_mods,
    crafted_mods,
    utility_mods,
    veiled_mods,
    flavour_text_lines,
    mutated_mods,
    hybrid_explicit_mods,
    sockets,
    ultimatum_mods,
    logbook_mods,
    socketed_items,
    socketed_item_properties,
    socketed_item_mods
FROM aggregated;
