#!/usr/bin/env python3
"""
Generate SQL INSERT statements for ml_mod_base_name_map_v1 from GGPK mods.min.json

Reads: /tmp/mods.min.json
Outputs: SQL INSERT statements to stdout

Each mod gets:
- mod_text_pattern: normalized (numbers → {N})
- mod_base_name: base name without tier digits
- mod_tier: tier number from mod ID
- mod_max_tier: max tier for this base name (computed)
- mod_max_value: max stat value at this tier
- mod_generation_type: 'prefix', 'suffix', or 'other'
- required_level: minimum level to spawn
"""

import json
import re
import sys
from collections import defaultdict


def extract_base_name(mod_id: str) -> str:
    """Remove trailing digits and underscores from mod ID."""
    return re.sub(r"[\d_]+$", "", mod_id)


def extract_tier(mod_id: str) -> int:
    """Extract tier number from trailing digits of mod ID."""
    match = re.search(r"(\d+)$", mod_id)
    return int(match.group(1)) if match else 1


def normalize_text_pattern(text: str) -> str:
    """Replace all numbers in text with {N} for pattern matching."""
    return re.sub(r"\d+", "{N}", text)


def compute_max_value(stats: list) -> float:
    """Compute maximum possible value from stats array."""
    if not stats:
        return 0.0
    return max(s.get("max", 0) for s in stats)


def main():
    # Load GGPK data
    with open("/tmp/mods.min.json") as f:
        mods = json.load(f)

    # Filter to item-domain prefix/suffix mods only
    item_mods = []
    for mod_id, mod in mods.items():
        if mod.get("domain") != "item":
            continue
        gen_type = mod.get("generation_type", "")
        if gen_type not in ("prefix", "suffix"):
            continue

        item_mods.append(
            {
                "mod_id": mod_id,
                "base_name": extract_base_name(mod_id),
                "tier": extract_tier(mod_id),
                "text": mod.get("text", ""),
                "max_value": compute_max_value(mod.get("stats", [])),
                "gen_type": gen_type,
                "required_level": mod.get("required_level", 1),
            }
        )

    # Compute max_tier per base_name
    base_max_tier = defaultdict(int)
    for mod in item_mods:
        base = mod["base_name"]
        if mod["tier"] > base_max_tier[base]:
            base_max_tier[base] = mod["tier"]

    # Add max_tier to each mod
    for mod in item_mods:
        mod["max_tier"] = base_max_tier[mod["base_name"]]

    # Output SQL INSERT statements
    print("-- Generated by generate_mod_category_sql.py")
    print(f"-- {len(item_mods)} item-domain prefix/suffix mods")
    print(
        "INSERT INTO poe_trade.ml_mod_base_name_map_v1 (mod_text_pattern, mod_base_name, mod_tier, mod_max_tier, mod_max_value, mod_generation_type, required_level, updated_at)"
    )
    print("VALUES")

    values = []
    for mod in item_mods:
        pattern = normalize_text_pattern(mod["text"])
        base = mod["base_name"]
        tier = mod["tier"]
        max_tier = mod["max_tier"]
        max_val = mod["max_value"]
        gen_type = mod["gen_type"]
        req_level = mod["required_level"]

        # Escape single quotes in pattern
        pattern_escaped = pattern.replace("'", "''")
        base_escaped = base.replace("'", "''")

        values.append(
            f"    ('{pattern_escaped}', '{base_escaped}', {tier}, {max_tier}, {max_val:.2f}, '{gen_type}', {req_level}, now64(3))"
        )

    print(",\n".join(values))
    print(";")


if __name__ == "__main__":
    main()
